@extends('layouts.app')
@section('title', 'Workforce overview')
@section('eyebrow', 'Your daily picture')
@section('description', 'The people, hours, and salaries across your companies.')
@section('actions')<form class="actions" method="GET"><label for="month" class="muted">Reporting month</label><input id="month" type="month" name="month" value="{{ $month }}" style="width:155px"><button class="btn secondary">Apply</button><a href="{{ route('dashboard') }}" class="btn link">Clear filter</a></form>@endsection
@section('content')
<div class="stats"><a class="stat stat-link" href="{{ route('employees.index') }}"><div class="label">Total employees <span class="stat-icon">♙</span></div><div class="value">{{ $stats['employees'] }}</div><div class="note">{{ $stats['active'] }} active across {{ $stats['companies'] }} companies · Open directory →</div></a><a class="stat stat-link" href="{{ route('timesheets.index', ['month' => $month, 'status' => 'approved']) }}"><div class="label">Approved regular hours · {{ \Carbon\Carbon::createFromFormat('!Y-m', $month)->format('M Y') }} <span class="stat-icon">◷</span></div><div class="value">{{ \App\Services\Pay::decimal($stats['regular']) }}</div><div class="note">{{ \App\Services\Pay::decimal($stats['overtime']) }} approved overtime hours · View →</div></a><a class="stat stat-link" href="{{ route('timesheets.index', ['month' => $month, 'status' => 'pending']) }}"><div class="label">Awaiting review · {{ \Carbon\Carbon::createFromFormat('!Y-m', $month)->format('M Y') }} <span class="stat-icon">≡</span></div><div class="value">{{ $stats['pending'] }}</div><div class="note">Pending timesheets & attendance for this month · Review →</div></a><a class="stat accent stat-link" href="{{ route('payrolls.index', ['month' => $month]) }}"><div class="label">Salary total · {{ \Carbon\Carbon::createFromFormat('!Y-m', $month)->format('M Y') }} · SAR <span>↗</span></div><div class="value">{{ \App\Services\Pay::money($stats['payroll']) }}</div><div class="note">{{ \App\Services\Pay::money($stats['paid']) }} marked paid for this month · Open payroll →</div></a></div>
<div class="grid-2"><div class="card"><div class="card-body"><div class="eyebrow">Rental manpower</div><h2>Hours that turn into earnings.</h2><p class="description" style="margin:10px 0 20px">Manage rental employees and calculate salary from approved hours.</p><div class="actions"><a class="btn" href="{{ route('employees.create') }}">+ Add rental employee</a><a class="btn secondary" href="{{ route('timesheets.index') }}">View timesheets →</a></div></div></div><div class="card"><div class="card-body"><div class="eyebrow">Own employees</div><h2>Your team. Their monthly salary.</h2><p class="description" style="margin:10px 0 20px">A separate directory, attendance, and fixed monthly salary workflow.</p><div class="actions"><a class="btn" href="{{ route('own-employees.create') }}">+ Add own employee</a><a class="btn secondary" href="{{ route('salaries.index') }}">Monthly salaries →</a></div></div></div></div>
<div class="columns"><div><div class="card"><div class="card-head"><h2>Recently added people</h2><span class="muted" style="font-size:11px">Latest 5 employees</span></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Company</th><th>Workforce</th><th>Status</th></tr></thead><tbody>@forelse($recent as $employee)<tr><td><div class="person"><img src="{{ route('employees.photo', $employee) }}" alt=""><div><a href="{{ route($employee->employment_type === 'own' ? 'own-employees.show' : 'employees.show', $employee) }}"><strong>{{ $employee->name }}</strong></a><span class="sub">{{ $employee->designation->name }}</span></div></div></td><td>{{ $employee->company->name }}</td><td>{{ $employee->employment_type === 'own' ? 'Own employee' : 'Rental' }}</td><td><span class="badge {{ $employee->status }}">{{ ucfirst($employee->status) }}</span></td></tr>@empty<tr><td colspan="4"><div class="empty"><strong>Your workforce starts here.</strong><p>Add your first employee to see them in this overview.</p></div></td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-head"><h2>Hours awaiting review</h2><span class="badge pending">{{ $stats['pending'] }} pending</span></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Date</th><th>Hours</th><th></th></tr></thead><tbody>@forelse($pending as $entry)<tr><td>{{ $entry->employee->name }}<span class="sub">{{ $entry->employee->employment_type === 'own' ? 'Own attendance' : 'Rental timesheet' }}</span></td><td>{{ $entry->work_date->format('d M Y') }}</td><td>{{ \App\Services\Pay::decimal($entry->regular_units + $entry->overtime_units) }}</td><td><a href="{{ route($entry->employee->employment_type === 'own' ? 'attendance.index' : 'timesheets.index', ['month' => $entry->work_date->format('Y-m'), 'status' => 'pending']) }}">{{ auth()->user()->isAdmin() ? 'Review' : 'View' }} →</a></td></tr>@empty<tr><td colspan="4"><div class="empty"><strong>All caught up.</strong><p>There are no hours waiting for review.</p></div></td></tr>@endforelse</tbody></table></div></div></div>
<div><div class="card"><div class="card-head"><h2>Your companies</h2><a href="{{ route('companies.index') }}">View all →</a></div><div class="card-body">@forelse($companies as $company)<div class="company-row"><div><strong>{{ $company->name }}</strong><br><small>{{ $company->is_active ? 'Active company' : 'Inactive company' }}</small></div><span class="badge">{{ $company->employees_count }} active</span></div>@empty<div class="empty"><strong>No companies assigned.</strong><p>Ask the Super Admin to assign a company to your account.</p></div>@endforelse</div></div><div class="card"><div class="card-body"><div class="eyebrow">How salary works</div><h3>Approve. Calculate. Record.</h3><p class="description">Rental pay comes from approved timesheet hours. Own employees receive their fixed monthly salary plus approved overtime.</p><p class="description" style="margin-top:14px">Manager, Admin, and Super Admin can generate payroll after all timesheets are reviewed. Admin and Super Admin approve salary slips; Super Admin records payment.</p></div></div></div></div>
@endsection
