@extends('layouts.app')
@section('title','Analytics dashboard')
@section('eyebrow','Workforce intelligence')
@section('description','People, productivity, approvals, payroll, and invoicing performance in one view.')
@section('actions')<form class="actions" method="GET"><label for="month" class="muted">Analysis month</label><input id="month" type="month" name="month" value="{{ $month }}" style="width:155px"><button class="btn secondary">Apply</button><a href="{{ route('dashboard') }}" class="btn link">Clear filter</a></form>@endsection
@section('content')
@php $monthLabel=\Carbon\Carbon::createFromFormat('!Y-m',$month)->format('F Y'); $changeBadge=function($value){return ($value>=0?'+':'').number_format($value,1).'%';}; @endphp
<div class="analytics-strip"><div><span>Reporting period</span><strong>{{ $monthLabel }}</strong></div><div><span>Active workforce</span><strong>{{ $stats['active'] }} / {{ $stats['employees'] }}</strong></div><div><span>Approval backlog</span><strong>{{ $stats['pending'] + $stats['payroll_pending'] }}</strong></div><div><span>Paid ratio</span><strong>{{ $stats['payroll'] ? number_format(($stats['paid']/$stats['payroll'])*100,1) : '0.0' }}%</strong></div><div><span>Invoice value</span><strong>SAR {{ \App\Services\Pay::money($invoiceStats['value']) }}</strong></div></div>

<div class="stats analytics-kpis">
<a class="stat stat-link" href="{{ route('employees.index') }}"><div class="label">Active employees <span class="stat-icon">♙</span></div><div class="value">{{ $stats['active'] }}</div><div class="metric-split"><span>{{ $stats['rental'] }} rental</span><span>{{ $stats['own'] }} own</span></div><div class="progress"><i style="width:{{ $stats['active'] ? ($stats['rental']/$stats['active'])*100 : 0 }}%"></i></div></a>
<a class="stat stat-link" href="{{ route('timesheets.index',['month'=>$month,'status'=>'approved']) }}"><div class="label">Approved hours <span class="trend {{ $changes['regular']>=0?'up':'down' }}">{{ $changeBadge($changes['regular']) }}</span></div><div class="value">{{ \App\Services\Pay::decimal($stats['regular']) }}</div><div class="note">Regular hours · previous {{ \App\Services\Pay::decimal($previous['regular']) }}</div></a>
<a class="stat stat-link" href="{{ route('timesheets.index',['month'=>$month,'status'=>'approved']) }}"><div class="label">Overtime hours <span class="trend {{ $changes['overtime']<=0?'up':'down' }}">{{ $changeBadge($changes['overtime']) }}</span></div><div class="value">{{ \App\Services\Pay::decimal($stats['overtime']) }}</div><div class="note">Previous month {{ \App\Services\Pay::decimal($previous['overtime']) }}</div></a>
<a class="stat accent stat-link" href="{{ route('payrolls.index',['month'=>$month]) }}"><div class="label">Payroll exposure · SAR <span class="trend {{ $changes['payroll']<=0?'up':'down' }}">{{ $changeBadge($changes['payroll']) }}</span></div><div class="value">{{ \App\Services\Pay::money($stats['payroll']) }}</div><div class="note">SAR {{ \App\Services\Pay::money($stats['paid']) }} paid · {{ $stats['payroll_pending'] }} awaiting approval</div></a>
</div>

<div class="grid-2 analytics-main">
<div class="card"><div class="card-head"><div><h2>Six-month operating trend</h2><span class="muted" style="font-size:11px">Approved hours compared with payroll value</span></div><span class="badge">{{ $trend->first()['label'] }}–{{ $trend->last()['label'] }}</span></div><div class="card-body"><div class="trend-legend"><span><i class="hours-dot"></i> Approved hours</span><span><i class="payroll-dot"></i> Payroll SAR</span></div><div class="analytics-chart">@foreach($trend as $point)<div class="chart-column"><div class="chart-bars"><i class="bar hours" style="height:{{ max(3,($point['hours']/$maxHours)*100) }}%" title="{{ \App\Services\Pay::decimal($point['hours']) }} hours"></i><i class="bar payroll" style="height:{{ max(3,($point['payroll']/$maxPayroll)*100) }}%" title="SAR {{ \App\Services\Pay::money($point['payroll']) }}"></i></div><strong>{{ $point['label'] }}</strong><span>{{ \App\Services\Pay::decimal($point['hours']) }}h</span></div>@endforeach</div></div></div>
<div class="card"><div class="card-head"><h2>Decision queue</h2><span class="badge {{ ($stats['pending']+$stats['payroll_pending'])?'pending':'approved' }}">{{ $stats['pending']+$stats['payroll_pending'] }} actions</span></div><div class="card-body"><a class="decision-row" href="{{ route('timesheets.index',['month'=>$month,'status'=>'pending']) }}"><span class="decision-icon amber">◷</span><div><strong>{{ $stats['pending'] }} timesheet entries</strong><small>Need approval or rejection before payroll</small></div><b>Review →</b></a><a class="decision-row" href="{{ route('payrolls.index',['month'=>$month,'status'=>'pending']) }}"><span class="decision-icon teal">▤</span><div><strong>{{ $stats['payroll_pending'] }} salary slips</strong><small>Generated and waiting for approval</small></div><b>Review →</b></a><a class="decision-row" href="{{ route('payrolls.index',['month'=>$month,'status'=>'approved']) }}"><span class="decision-icon navy">✓</span><div><strong>{{ $stats['payroll_approved'] }} approved salaries</strong><small>Ready to be recorded as paid</small></div><b>Open →</b></a><a class="decision-row" href="{{ route('invoicing.index',['status'=>'draft']) }}"><span class="decision-icon gray">◫</span><div><strong>{{ $invoiceStats['draft'] }} invoice drafts</strong><small>Awaiting approval and permanent numbering</small></div><b>Open →</b></a></div></div>
</div>

<div class="columns"><div>
<div class="card"><div class="card-head"><div><h2>Company performance</h2><span class="muted" style="font-size:11px">Workforce size, monthly payroll, and approval exceptions</span></div><a href="{{ route('companies.index') }}">Company directory →</a></div><div class="table-wrap"><table><thead><tr><th>Company</th><th>Active employees</th><th>Share</th><th>Monthly payroll</th><th>Pending entries</th></tr></thead><tbody>@forelse($companyAnalytics as $row)<tr><td><strong>{{ $row['company']->name }}</strong><span class="sub">{{ $row['company']->location }}</span></td><td>{{ $row['employees'] }}</td><td><div class="table-meter"><i style="width:{{ $stats['active']?($row['employees']/$stats['active'])*100:0 }}%"></i></div><span class="sub">{{ $stats['active']?number_format(($row['employees']/$stats['active'])*100,1):0 }}%</span></td><td><strong>SAR {{ \App\Services\Pay::money($row['payroll']) }}</strong></td><td><span class="badge {{ $row['pending']?'pending':'approved' }}">{{ $row['pending'] }}</span></td></tr>@empty<tr><td colspan="5"><div class="empty">No company analytics available.</div></td></tr>@endforelse</tbody></table></div></div>
<div class="card"><div class="card-head"><h2>Hours awaiting review</h2><span class="badge pending">{{ $stats['pending'] }} pending</span></div><div class="table-wrap"><table><thead><tr><th>Employee</th><th>Date</th><th>Hours</th><th></th></tr></thead><tbody>@forelse($pending as $entry)<tr><td>{{ $entry->employee->name }}<span class="sub">{{ $entry->employee->employment_type==='own'?'Own attendance':'Rental timesheet' }}</span></td><td>{{ $entry->work_date->format('d M Y') }}</td><td>{{ \App\Services\Pay::decimal($entry->regular_units+$entry->overtime_units) }}</td><td><a href="{{ route($entry->employee->employment_type==='own'?'attendance.index':'timesheets.index',['month'=>$month,'status'=>'pending']) }}">{{ auth()->user()->canApprove()?'Review':'View' }} →</a></td></tr>@empty<tr><td colspan="4"><div class="empty"><strong>All caught up.</strong><p>No entries are waiting for review.</p></div></td></tr>@endforelse</tbody></table></div></div>
</div><div>
<div class="card"><div class="card-head"><h2>Workforce composition</h2><span class="badge">{{ $stats['active'] }} active</span></div><div class="card-body"><div class="donut-wrap"><div class="donut" style="--rental:{{ $stats['active']?($stats['rental']/$stats['active'])*100:0 }}%"><div><strong>{{ $stats['active'] }}</strong><span>employees</span></div></div><div class="donut-legend"><a href="{{ route('employees.index') }}"><i class="rental"></i><span>Rental</span><strong>{{ $stats['rental'] }}</strong></a><a href="{{ route('own-employees.index') }}"><i class="own"></i><span>Own</span><strong>{{ $stats['own'] }}</strong></a><div><i class="inactive"></i><span>Inactive</span><strong>{{ $stats['employees']-$stats['active'] }}</strong></div></div></div></div></div>
<div class="card"><div class="card-head"><h2>Invoice analytics</h2><a href="{{ route('invoicing.index') }}">Open module →</a></div><div class="card-body"><div class="mini-metrics"><div><span>Approved</span><strong>{{ $invoiceStats['approved'] }}</strong></div><div><span>Paid</span><strong>{{ $invoiceStats['paid'] }}</strong></div><div><span>Value</span><strong>SAR {{ \App\Services\Pay::money($invoiceStats['value']) }}</strong></div></div><p class="help">Showcase ZATCA module remains in demo mode; values are not submitted to ZATCA.</p></div></div>
<div class="card"><div class="card-head"><h2>Recently added people</h2><a href="{{ route('employees.index') }}">All employees →</a></div><div class="card-body">@forelse($recent as $employee)<div class="company-row"><div><a href="{{ route($employee->employment_type==='own'?'own-employees.show':'employees.show',$employee) }}"><strong>{{ $employee->name }}</strong></a><br><small>{{ $employee->designation->name }} · {{ $employee->company->name }}</small></div><span class="badge {{ $employee->status }}">{{ ucfirst($employee->status) }}</span></div>@empty<div class="empty">No employees available.</div>@endforelse</div></div>
</div></div>
@endsection
