<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Salary Slip - {{ $payroll->employee_name }}</title>
<style>
@page{margin:22px 30px 36px}*{box-sizing:border-box}body{font-family:'DejaVu Sans',sans-serif;color:#111;font-size:9px;margin:0}.slip{border:1.5px solid #333;width:100%;border-collapse:collapse}.slip td{border:1px solid #333}.olive{background:#4d6325;color:#fff}.brand{width:25%;padding:12px 16px;color:#fff}.brand strong{display:block;font-size:17px;letter-spacing:1px}.brand span{font-size:6px;letter-spacing:1.2px;text-transform:uppercase}.title{width:46%;text-align:center;padding:8px}.title h1{font-size:23px;letter-spacing:1px;margin:0 0 5px}.title div{border-top:1px solid #333;padding-top:5px;font-size:11px;font-weight:bold}.confidential{width:29%;text-align:center;font-size:18px;font-weight:bold;letter-spacing:.5px;background:#dfe8c9;color:#1c250f}.identity{width:100%;border-collapse:collapse}.identity td{width:50%;padding:8px 14px;vertical-align:top;border:1px solid #333}.info{width:100%;border-collapse:collapse}.info td{border:0;padding:2px 0}.info .label{width:34%;color:#30372a}.info .colon{width:5%}.info .value{font-weight:bold}.breakdown{width:100%;border-collapse:collapse;table-layout:fixed}.breakdown th{background:#4d6325;color:#fff;border:1px solid #333;padding:6px;font-size:10px}.breakdown th:first-child{width:50%}.breakdown th:nth-child(2),.breakdown th:nth-child(3){width:25%}.breakdown td{border-left:1px solid #333;border-right:1px solid #333;padding:6px 14px;height:23px}.breakdown .amount{text-align:right;font-weight:bold}.spacer td{height:34px}.totals{width:100%;border-collapse:collapse}.totals td{border:1px solid #333;padding:7px 14px;font-weight:bold}.totals .description{width:50%}.totals .amount{width:25%;text-align:right;font-size:11px}.payment{width:100%;border-collapse:collapse}.payment td{border:1px solid #333;padding:7px 14px}.payment-info{width:50%}.net-label{width:25%;background:#4d6325;color:#fff;text-align:right;font-weight:bold;font-size:12px}.net-value{width:25%;background:#4d6325;color:#fff;text-align:right;font-weight:bold;font-size:15px}.approval-footer{position:fixed;left:0;right:0;bottom:0}.approval{width:100%;border-collapse:separate;border-spacing:32px 0;margin-top:0}.approval>tbody>tr>td{width:50%;border:0;vertical-align:top;padding:0}.approval-box{min-height:76px}.signature-line{border-top:1px solid #555;padding-top:4px;margin-top:38px;color:#555}.approval-detail{width:100%;border-collapse:collapse}.approval-detail td{border:0;vertical-align:top}.approval-detail .signatory{width:72%;padding-right:10px}.seal-cell{width:28%;text-align:center;position:relative;top:-8px}.seal{display:inline-block;width:66px;height:66px;border:3px double #4d6325;border-radius:38px;color:#4d6325;text-align:center;font-weight:bold;text-transform:uppercase;padding-top:10px;font-size:6px;line-height:1.3}.seal .check{font-size:13px;line-height:13px}.footer{font-size:6px;color:#666;margin-top:7px;border-top:1px solid #ccc;padding-top:5px}
.breakdown th{padding:4px}.breakdown td{padding:2px 12px;height:16px}.spacer td{height:4px}.identity td{padding:6px 12px}.approval{margin-top:4px}.approval-box{min-height:58px}.signature-line{margin-top:24px}.seal{width:54px;height:54px;border-radius:30px;padding-top:7px;font-size:5px}.seal .check{font-size:11px;line-height:11px}.footer{margin-top:4px;padding-top:4px}
</style></head><body>
@include('pdf.company-brand')
@php $monthLabel = \Carbon\Carbon::createFromFormat('!Y-m', $payroll->month)->format('F Y'); $attested = in_array($payroll->status, ['approved','paid']); $gross = $payroll->regular_pay_cents + $payroll->overtime_pay_cents + $payroll->allowance_cents + $payroll->meal_allowance_cents + $payroll->transportation_allowance_cents + $payroll->housing_allowance_cents + $payroll->medical_allowance_cents; $totalDeductions = $payroll->deduction_cents + $payroll->advance_deduction_cents + $payroll->retirement_insurance_cents + $payroll->tax_cents; $printNote = $payroll->notes ? \Illuminate\Support\Str::limit(preg_replace('/\s+/', ' ', trim($payroll->notes)), 180, '... [full note in system]') : null; @endphp
<table class="slip"><tr><td class="brand olive"><strong>{{ strtoupper($documentBrand ? $documentBrand->company_name : $payroll->company_name) }}</strong><span>{{ $documentBrand && $documentBrand->tagline ? $documentBrand->tagline : 'Workforce management' }}</span></td><td class="title"><h1>SALARY SLIP</h1><div>{{ $monthLabel }}</div></td><td class="confidential">CONFIDENTIAL</td></tr></table>
<table class="identity"><tr><td><table class="info"><tr><td class="label">Name</td><td class="colon">:</td><td class="value">{{ $payroll->employee_name }}</td></tr><tr><td class="label">Employee ID</td><td class="colon">:</td><td class="value">EMP-{{ str_pad($payroll->employee_id, 4, '0', STR_PAD_LEFT) }}</td></tr><tr><td class="label">Iqama Number</td><td class="colon">:</td><td class="value">{{ $payroll->iqama_number }}</td></tr></table></td><td><table class="info"><tr><td class="label">Title</td><td class="colon">:</td><td class="value">{{ $payroll->designation_name }}</td></tr><tr><td class="label">Directorate</td><td class="colon">:</td><td class="value">{{ $payroll->directorate ?: '-' }}</td></tr><tr><td class="label">Department</td><td class="colon">:</td><td class="value">{{ $payroll->department ?: '-' }}</td></tr></table></td></tr></table>
<table class="breakdown"><thead><tr><th>Description</th><th>Earnings (SAR)</th><th>Deductions (SAR)</th></tr></thead><tbody>
<tr><td>Basic Salary</td><td class="amount">{{ \App\Services\Pay::money($payroll->regular_pay_cents) }}</td><td></td></tr>
<tr><td>Overtime Pay</td><td class="amount">{{ \App\Services\Pay::money($payroll->overtime_pay_cents) }}</td><td></td></tr>
<tr><td>Meal Allowance</td><td class="amount">{{ \App\Services\Pay::money($payroll->meal_allowance_cents) }}</td><td></td></tr>
<tr><td>Transportation Allowance</td><td class="amount">{{ \App\Services\Pay::money($payroll->transportation_allowance_cents) }}</td><td></td></tr>
<tr><td>Housing Allowance</td><td class="amount">{{ \App\Services\Pay::money($payroll->housing_allowance_cents) }}</td><td></td></tr>
<tr><td>Medical Allowance</td><td class="amount">{{ \App\Services\Pay::money($payroll->medical_allowance_cents) }}</td><td></td></tr>
@if($payroll->allowance_cents)<tr><td>Other Allowances / Adjustment</td><td class="amount">{{ \App\Services\Pay::money($payroll->allowance_cents) }}</td><td></td></tr>@endif
<tr><td>Retirement Insurance</td><td></td><td class="amount">{{ \App\Services\Pay::money($payroll->retirement_insurance_cents) }}</td></tr>
<tr><td>Tax</td><td></td><td class="amount">{{ \App\Services\Pay::money($payroll->tax_cents) }}</td></tr>
@if($payroll->deduction_cents)<tr><td>Other Deductions / Adjustment</td><td></td><td class="amount">{{ \App\Services\Pay::money($payroll->deduction_cents) }}</td></tr>@endif
@if($payroll->advance_deduction_cents)<tr><td>Employee Advance Repayment</td><td></td><td class="amount">{{ \App\Services\Pay::money($payroll->advance_deduction_cents) }}</td></tr>@endif
@if($printNote)<tr><td colspan="3"><strong>Note:</strong> {{ $printNote }}</td></tr>@endif
<tr class="spacer"><td></td><td></td><td></td></tr>
</tbody></table>
<table class="totals"><tr><td class="description">Total</td><td class="amount">{{ \App\Services\Pay::money($gross) }}</td><td class="amount">{{ \App\Services\Pay::money($totalDeductions) }}</td></tr></table>
<table class="payment"><tr><td class="payment-info"><strong>Payment Date</strong>&nbsp;&nbsp;:&nbsp;&nbsp;{{ $payroll->paid_at ? $payroll->paid_at->format('d F Y') : 'Not recorded' }}</td><td class="net-label">NET PAY</td><td class="net-value">SAR {{ \App\Services\Pay::money($payroll->net_pay_cents) }}</td></tr></table>
<div class="approval-footer"><table class="approval"><tr><td><div class="approval-box"><strong>RECEIVED BY EMPLOYEE</strong><div class="signature-line"><strong>{{ $payroll->employee_name }}</strong><br>Employee signature and date</div></div></td><td><div class="approval-box"><strong>AUTHORIZED APPROVAL</strong><table class="approval-detail"><tr><td class="signatory"><div class="signature-line"><strong>{{ $attested && $payroll->approver ? $payroll->approver->name : 'Authorized Signatory' }}</strong><br>{{ $attested ? 'Electronically approved '.optional($payroll->approved_at)->format('d F Y, H:i') : 'Pending administrator approval' }}</div></td><td class="seal-cell"><div class="seal"><div class="check">{{ $attested ? '✓' : '!' }}</div>{{ $attested ? 'Attested' : 'Pending' }}<br>{{ $monthLabel }}</div></td></tr></table></div></td></tr></table><div class="footer">This confidential salary slip is system generated for the named employee. The attestation mark appears only after payroll approval. Amounts are in Saudi Riyals (SAR).</div></div>
</body></html>
