<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><title>Salary Payslip - {{ $payroll->employee_name }}</title>@include('pdf.style')
<style>
@page{margin:30px 38px 48px}.slip-header{border-top:7px solid #123b43;padding:18px 0 14px;border-bottom:1px solid #cddbd8;width:100%}.brand{font-size:19px;font-weight:bold;color:#123b43;letter-spacing:.3px}.document-title{text-align:right;font-size:24px;font-weight:bold;color:#123b43}.document-subtitle{text-align:right;color:#64777a;font-size:8px;text-transform:uppercase;letter-spacing:1.4px}.summary{margin:18px 0;width:100%;border-collapse:collapse}.summary td{width:25%;padding:10px 12px;background:#f2f6f4;border-right:3px solid white;vertical-align:top}.summary-label{font-size:7px;color:#687b7e;text-transform:uppercase;letter-spacing:.7px}.summary-value{font-size:10px;font-weight:bold;color:#18383d;margin-top:3px}.section-title{font-size:9px;text-transform:uppercase;letter-spacing:1.1px;color:#2c655f;border-bottom:2px solid #2c655f;padding-bottom:5px;margin:18px 0 8px}.earnings{width:100%;border-collapse:collapse}.earnings th{background:#123b43;color:white;text-transform:uppercase;font-size:7px;letter-spacing:.7px;padding:8px 10px}.earnings td{padding:9px 10px;border-bottom:1px solid #dce6e3}.earnings .money{text-align:right;font-weight:bold}.net-box{width:100%;border-collapse:collapse;margin-top:12px}.net-box td{background:#e3eee9;padding:13px 14px;color:#123b43;font-weight:bold}.net-box .net-amount{text-align:right;font-size:20px}.approval{width:100%;border-collapse:collapse;margin-top:22px;page-break-inside:avoid}.approval td{vertical-align:middle}.signature{width:65%;padding-right:30px}.signature-line{border-top:1px solid #6d7e80;margin-top:28px;padding-top:5px;color:#586b6e}.seal-cell{width:35%;text-align:center}.seal{display:inline-block;width:104px;height:104px;border:4px double #24756c;border-radius:58px;color:#24756c;text-align:center;font-weight:bold;text-transform:uppercase}.seal-inner{margin:8px;width:80px;height:80px;border:1px solid #24756c;border-radius:45px;padding-top:14px;box-sizing:border-box;font-size:7px;line-height:1.35;letter-spacing:.5px}.seal-check{font-size:20px;line-height:20px}.seal.pending{border-color:#8b9495;color:#758183}.seal.pending .seal-inner{border-color:#8b9495}.legal{font-size:7px;color:#738285;margin-top:16px;border-top:1px solid #dce5e2;padding-top:8px}.hours{font-size:7px}.hours th,.hours td{padding:5px 7px}.status-pill{display:inline-block;padding:3px 8px;background:#e3eee9;color:#21685f;font-size:7px;font-weight:bold;text-transform:uppercase;letter-spacing:.7px}.status-pill.pending{background:#f4ead5;color:#8a641f}.notes-box{padding:9px 11px;background:#f4f7f5;border-left:3px solid #2c655f;margin-top:10px}
</style></head><body>
@php $monthLabel = \Carbon\Carbon::createFromFormat('!Y-m', $payroll->month)->format('F Y'); $attested = in_array($payroll->status, ['approved', 'paid']); @endphp
<table class="slip-header"><tr><td><div class="eyebrow">{{ $payroll->company_name }}</div><div class="brand">MANPOWER</div><div class="muted">Human Resources &amp; Payroll Services</div></td><td><div class="document-title">SALARY PAYSLIP</div><div class="document-subtitle">Confidential employee statement</div></td></tr></table>
<table class="summary"><tr><td><div class="summary-label">Employee</div><div class="summary-value">{{ $payroll->employee_name }}</div></td><td><div class="summary-label">Iqama / Employee ID</div><div class="summary-value">{{ $payroll->iqama_number }}</div></td><td><div class="summary-label">Pay period</div><div class="summary-value">{{ $monthLabel }}</div></td><td><div class="summary-label">Payslip number</div><div class="summary-value">PS-{{ str_pad($payroll->id, 6, '0', STR_PAD_LEFT) }}</div></td></tr><tr><td><div class="summary-label">Designation</div><div class="summary-value">{{ $payroll->designation_name ?: 'Not specified' }}</div></td><td><div class="summary-label">Employment</div><div class="summary-value">Rental - hourly</div></td><td colspan="2" class="company-cell"><div class="summary-label">Company</div><div class="summary-value">{{ $payroll->company_name }}</div></td></tr></table>
<div class="section-title">Salary calculation</div><table class="earnings"><thead><tr><th>Description</th><th style="text-align:right">Earnings</th><th style="text-align:right">Deductions</th></tr></thead><tbody><tr><td>{{ $payroll->employment_type === 'own' ? 'Fixed monthly base salary' : 'Regular pay ('.\App\Services\Pay::decimal($payroll->regular_units).' approved hours)' }}</td><td class="money">SAR {{ \App\Services\Pay::money($payroll->regular_pay_cents) }}</td><td></td></tr><tr><td>Overtime pay ({{ \App\Services\Pay::decimal($payroll->overtime_units) }} hours)</td><td class="money">SAR {{ \App\Services\Pay::money($payroll->overtime_pay_cents) }}</td><td></td></tr><tr><td>Allowances</td><td class="money">SAR {{ \App\Services\Pay::money($payroll->allowance_cents) }}</td><td></td></tr><tr><td>Deductions</td><td></td><td class="money">SAR {{ \App\Services\Pay::money($payroll->deduction_cents) }}</td></tr></tbody></table>
<table class="net-box"><tr><td>NET SALARY PAYABLE</td><td class="net-amount">SAR {{ \App\Services\Pay::money($payroll->net_pay_cents) }}</td></tr></table>
@if($payroll->notes)<div class="notes-box"><strong>Payroll note</strong><br>{{ $payroll->notes }}</div>@endif
<table class="approval"><tr><td class="signature"><div class="summary-label">Authorized approval</div><div class="signature-line"><strong>{{ $attested && $payroll->approver ? $payroll->approver->name : 'Authorized Signatory' }}</strong><br>@if($attested)Approved electronically on {{ optional($payroll->approved_at)->format('d F Y, H:i') ?: 'recorded approval date' }}@else Pending administrator approval @endif</div></td><td class="seal-cell"><div class="seal {{ $attested ? '' : 'pending' }}"><div class="seal-inner"><div class="seal-check">{{ $attested ? '✓' : '!' }}</div>{{ $attested ? 'Attested' : 'Not attested' }}<br>{{ $payroll->company_name }}<br>{{ $monthLabel }}</div></div></td></tr></table>
<div class="legal">This system-generated payslip is confidential. The attestation mark appears only after payroll approval. It confirms approval within the Manpower system and does not replace external government or bank certification. @if($payroll->paid_at) Payment recorded {{ $payroll->paid_at->format('d F Y, H:i') }} (Riyadh time). @endif</div>
</body></html>
