@extends('layouts.app')
@section('title','ZATCA integration')
@section('eyebrow','Independent compliance module')
@section('description','Onboarding and FATOORA connectivity are isolated from normal invoice operations.')
@section('actions')<a class="btn secondary" href="{{ route('invoicing.index') }}">Open invoice platform →</a>@endsection
@section('content')
<div class="notice info"><strong>Integration not configured.</strong> The invoice platform remains fully available with local approval, PDF, XML and invoice QR generation. No invoice is currently sent to ZATCA.</div>
<div class="stats"><div class="stat"><div class="label">Connection</div><div class="value" style="font-size:1.3rem">Inactive</div><div class="note">No FATOORA API calls</div></div><div class="stat"><div class="label">Compliance CSID</div><div class="value" style="font-size:1.3rem">Not issued</div><div class="note">Onboarding pending</div></div><div class="stat"><div class="label">Production CSID</div><div class="value" style="font-size:1.3rem">Not issued</div><div class="note">Production locked</div></div><div class="stat accent"><div class="label">ZATCA submissions</div><div class="value">{{ $stats['submitted'] }}</div><div class="note">No automatic reporting</div></div></div>
<div class="grid-2"><div class="card"><div class="card-head"><h2>Required from the client</h2><span class="badge pending">Pending</span></div><div class="card-body"><div class="company-row"><div><strong>Registered identity</strong><small>Arabic/English legal name, VAT certificate, CR and national address</small></div><span>1</span></div><div class="company-row"><div><strong>FATOORA access</strong><small>Authorized taxpayer representative retains the portal password</small></div><span>2</span></div><div class="company-row"><div><strong>Onboarding OTP</strong><small>Generated only during the scheduled onboarding session</small></div><span>3</span></div><div class="company-row"><div><strong>Phase 2 confirmation</strong><small>Client confirms the applicable ZATCA integration wave</small></div><span>4</span></div></div></div>
<div class="card"><div class="card-head"><h2>Activation stages</h2><span class="badge">Separate workflow</span></div><div class="card-body"><div class="company-row"><div><strong>1. Generate key and CSR</strong><small>Private key remains encrypted on the production server</small></div><span class="badge pending">Locked</span></div><div class="company-row"><div><strong>2. Compliance CSID</strong><small>Validate B2B, B2C, credit and debit documents</small></div><span class="badge pending">Locked</span></div><div class="company-row"><div><strong>3. Production CSID</strong><small>Enable authenticated clearance and reporting APIs</small></div><span class="badge pending">Locked</span></div><div class="company-row"><div><strong>4. Go live</strong><small>Activate monitoring, retries and certificate expiry alerts</small></div><span class="badge pending">Locked</span></div></div></div></div>
<div class="card"><div class="card-head"><h2>Current seller reference</h2><span class="badge">Invoice platform</span></div><div class="card-body"><dl class="detail-list"><div><dt>Legal name</dt><dd>{{ $settings->legal_name }}<span class="sub">{{ $settings->legal_name_ar }}</span></dd></div><div><dt>VAT number</dt><dd>{{ $settings->vat_number }}</dd></div><div><dt>Commercial registration</dt><dd>{{ $settings->commercial_registration }}</dd></div><div><dt>Registered address</dt><dd>{{ $settings->address }}, {{ $settings->city }} {{ $settings->postal_code }}</dd></div></dl><p class="help">These values support normal invoice output only. They are not treated as verified ZATCA credentials.</p></div></div>
@endsection
