@extends('layouts.app')
@section('title','Global document branding')
@section('eyebrow','Organization · Superadmin settings')
@section('description','Manage the logo and company identity used across PDFs, invoices, timesheets, payslips, CVs, audit reports, and receipts.')
@section('content')
<form method="POST" action="{{ route('document-branding.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="grid-2"><div class="card"><div class="card-head"><h2>Logo and identity</h2><span class="badge">Superadmin only</span></div><div class="card-body"><div class="form-grid"><div class="field full"><label>Company logo</label><input type="file" name="logo" accept=".jpg,.jpeg,.png,.webp"><span class="help">PNG, JPG or WebP; maximum 2 MB. A professional “SS” placeholder is used when blank.</span></div>@if($settings->logo_path)<div class="field full"><label><input type="checkbox" name="remove_logo" value="1"> Remove current logo and use placeholder</label></div>@endif<div class="field"><label>Company name *</label><input name="company_name" required maxlength="180" value="{{ old('company_name',$settings->company_name) }}"></div><div class="field"><label>Tagline</label><input name="tagline" maxlength="180" value="{{ old('tagline',$settings->tagline) }}"></div><div class="field"><label>VAT number</label><input name="vat_number" maxlength="30" value="{{ old('vat_number',$settings->vat_number) }}"></div><div class="field"><label>Commercial registration</label><input name="commercial_registration" maxlength="30" value="{{ old('commercial_registration',$settings->commercial_registration) }}"></div></div></div></div>
<div class="card"><div class="card-head"><h2>Contact and receipt footer</h2></div><div class="card-body"><div class="form-grid"><div class="field full"><label>Default Safety Shop location</label><select name="default_location_id"><option value="">Select active location</option>@foreach($shopLocations as $location)<option value="{{ $location->id }}" {{ (int)old('default_location_id',$settings->default_location_id)===$location->id?'selected':'' }}>{{ $location->name }}</option>@endforeach</select><span class="help">Checkout uses this location automatically and does not show users the other locations.</span></div><div class="field"><label>Phone</label><input name="phone" maxlength="50" value="{{ old('phone',$settings->phone) }}"></div><div class="field"><label>Email</label><input name="email" type="email" maxlength="150" value="{{ old('email',$settings->email) }}"></div><div class="field full"><label>Website</label><input name="website" type="url" maxlength="150" placeholder="https://example.com" value="{{ old('website',$settings->website) }}"></div><div class="field full"><label>Address</label><input name="address" maxlength="500" value="{{ old('address',$settings->address) }}"></div><div class="field"><label>City</label><input name="city" maxlength="100" value="{{ old('city',$settings->city) }}"></div><div class="field"><label>Postal code</label><input name="postal_code" maxlength="20" value="{{ old('postal_code',$settings->postal_code) }}"></div><div class="field full"><label>Footer message</label><textarea name="footer_text" maxlength="500">{{ old('footer_text',$settings->footer_text) }}</textarea></div></div></div></div></div>
<div class="form-footer"><button class="btn">Save global document branding</button></div></form>
@endsection
