@extends('layouts.app')
@section('title','SaaS vouchers')
@section('eyebrow','Platform administration')
@section('description','Issue subscription vouchers and control company access.')
@section('content')
@if(session('new_voucher'))<div class="notice"><strong>Copy this voucher now:</strong><div style="font-size:20px;margin-top:8px;letter-spacing:1px">{{ session('new_voucher') }}</div><span class="help">Only its secure hash is stored. The code cannot be displayed again.</span></div>@endif
<div class="card"><div class="card-head"><h2>Issue voucher</h2></div><div class="card-body"><form method="POST" action="{{ route('saas.vouchers.store') }}">@csrf<div class="form-grid">
<div class="field"><label>Duration (days) *</label><input type="number" name="duration_days" min="1" max="3650" value="{{ old('duration_days',30) }}" required></div>
<div class="field"><label>Assign to company</label><select name="assigned_company_id"><option value="">Any company</option>@foreach($companies as $company)<option value="{{ $company->id }}" {{ old('assigned_company_id')==$company->id?'selected':'' }}>{{ $company->name }} · {{ $company->company_code }}</option>@endforeach</select></div>
<div class="field"><label>Redeem before</label><input type="date" name="valid_until" min="{{ today()->format('Y-m-d') }}" value="{{ old('valid_until',today()->addDays(90)->format('Y-m-d')) }}"></div>
</div><div class="form-footer"><button class="btn">Generate voucher</button></div></form></div></div>

<div class="card"><div class="card-head"><h2>Company access</h2><span class="badge">{{ $companies->count() }} companies</span></div><div class="table-wrap"><table><thead><tr><th>Company</th><th>State</th><th>Expiry</th><th>Control</th></tr></thead><tbody>@forelse($companies as $company)<tr><td><strong>{{ $company->name }}</strong><span class="sub">{{ $company->company_code }}</span></td><td><span class="badge {{ $company->hasApplicationAccess()?'active':'inactive' }}">{{ $company->subscriptionState() }}</span></td><td>{{ optional($company->subscription_expires_at)->format('d M Y') ?: 'No subscription' }}</td><td><div class="actions">@if($company->subscription_status==='suspended')<form method="POST" action="{{ route('saas.companies.status',$company) }}">@csrf @method('PUT')<input type="hidden" name="subscription_status" value="active"><button class="btn secondary small">Restore access</button></form>@else<form method="POST" action="{{ route('saas.companies.status',$company) }}" data-confirm="Remove application access for every user in this company? Their records and accounts will be preserved.">@csrf @method('PUT')<input type="hidden" name="subscription_status" value="suspended"><button class="btn danger small">Remove access</button></form>@endif</div></td></tr>@empty<tr><td colspan="4"><div class="empty">Create a company before issuing assigned vouchers.</div></td></tr>@endforelse</tbody></table></div></div>

<div class="card"><div class="card-head"><h2>Voucher ledger</h2></div><div class="table-wrap"><table><thead><tr><th>Code</th><th>Duration</th><th>Assigned</th><th>Status</th><th>Valid until</th><th>Created by</th></tr></thead><tbody>@forelse($vouchers as $voucher)<tr><td>{{ $voucher->code_prefix }}…</td><td>{{ $voucher->duration_days }} days</td><td>{{ optional($voucher->assignedCompany)->name ?: 'Any company' }}</td><td><span class="badge {{ $voucher->status==='unused'?'active':'inactive' }}">{{ strtoupper($voucher->status) }}</span>@if($voucher->redeemedCompany)<span class="sub">{{ $voucher->redeemedCompany->name }}</span>@endif</td><td>{{ optional($voucher->valid_until)->format('d M Y') ?: 'No limit' }}</td><td>{{ optional($voucher->creator)->name }}</td></tr>@empty<tr><td colspan="6"><div class="empty">No vouchers issued.</div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['items'=>$vouchers])</div>

<div class="card"><div class="card-head"><h2>Recent redemptions</h2></div><div class="table-wrap"><table><thead><tr><th>Company</th><th>Voucher</th><th>Previous expiry</th><th>New expiry</th><th>Redeemed by</th></tr></thead><tbody>@forelse($redemptions as $item)<tr><td>{{ $item->company->name }}</td><td>{{ $item->voucher->code_prefix }}…</td><td>{{ optional($item->previous_expiry)->format('d M Y') ?: 'None' }}</td><td>{{ $item->new_expiry->format('d M Y') }}</td><td>{{ $item->redeemer->name }}<span class="sub">{{ $item->redeemed_at->format('d M Y H:i') }}</span></td></tr>@empty<tr><td colspan="5"><div class="empty">No vouchers redeemed.</div></td></tr>@endforelse</tbody></table></div></div>
@endsection
