@extends('layouts.app')
@section('title','Sale receipt SALE-'.$sale->id)
@section('eyebrow','Safety shop · Sale receipt')
@section('description','Stock sale receipt · '.$sale->created_at->format('d M Y H:i'))
@section('content')
<div class="shop-no-print">@include('safety-shop.shared.nav')</div>
<div class="receipt-actions shop-no-print"><a class="btn secondary" href="{{ route('safety-shop.sales.create') }}">New sale</a><button class="btn" id="shop-print-receipt" type="button">Print receipt</button></div>
<article class="card safety-shop-receipt">
<header class="receipt-header"><div class="receipt-brand">@if($receiptLogo)<img class="receipt-logo" src="{{ $receiptLogo }}" alt="{{ $receiptSettings->company_name }} logo">@else<span class="receipt-mark">SS</span>@endif<div><strong>{{ strtoupper($receiptSettings->company_name) }}</strong><small>{{ $receiptSettings->tagline ?: 'Safety equipment and stock sales' }}</small>@if($receiptSettings->commercial_registration || $receiptSettings->vat_number)<small>@if($receiptSettings->commercial_registration)CR {{ $receiptSettings->commercial_registration }}@endif @if($receiptSettings->commercial_registration && $receiptSettings->vat_number) · @endif @if($receiptSettings->vat_number)VAT {{ $receiptSettings->vat_number }}@endif</small>@endif</div></div><div class="receipt-title"><span>Sales receipt</span><strong>SALE-{{ str_pad($sale->id,6,'0',STR_PAD_LEFT) }}</strong><small>Original customer copy</small></div></header>
<section class="receipt-meta"><div><span>Receipt date</span><strong>{{ $sale->created_at->format('d M Y') }}</strong><small>{{ $sale->created_at->format('h:i A') }}</small></div><div><span>Customer</span><strong>{{ $sale->customer }}</strong><small>{{ $sale->customer_phone ?: 'Mobile not provided' }}</small>@if($sale->customer_email)<small>{{ $sale->customer_email }}</small>@endif @if($sale->customer_address)<small>{{ $sale->customer_address }}</small>@endif</div><div><span>Shop location</span><strong>{{ $sale->location->name }}</strong><small>Stock issued at point of sale</small></div><div><span>Processed by</span><strong>{{ $sale->creator->name }}</strong><small>{{ ucfirst(str_replace('_',' ',$sale->creator->role)) }}</small></div></section>
<div class="receipt-items table-wrap"><table><thead><tr><th>#</th><th>Product / description</th><th>Qty</th><th>Unit price</th><th>Amount SAR</th></tr></thead><tbody>@foreach($sale->lines as $line)<tr><td>{{ $loop->iteration }}</td><td><strong>{{ $line->name }}</strong><span class="sub">SKU {{ $line->sku }} · {{ $line->barcode ?: 'No barcode' }}</span></td><td>{{ number_format($line->quantity) }} {{ $line->unit }}</td><td>{{ \App\Services\Pay::money($line->price_cents) }}</td><td><strong>{{ \App\Services\Pay::money($line->total_cents) }}</strong></td></tr>@endforeach</tbody></table></div>
<section class="receipt-financials"><div class="receipt-payment"><h3>Payment details</h3>@if($sale->cash_cents)<div><span>Cash</span><strong>SAR {{ \App\Services\Pay::money($sale->cash_cents) }}</strong></div>@endif @if($sale->card_cents)<div><span>Card</span><strong>SAR {{ \App\Services\Pay::money($sale->card_cents) }}</strong></div>@endif @if($sale->bank_cents)<div><span>Bank transfer</span><strong>SAR {{ \App\Services\Pay::money($sale->bank_cents) }}</strong></div>@endif<div class="payment-total"><span>Total received</span><strong>SAR {{ \App\Services\Pay::money($sale->paid_cents) }}</strong></div><div><span>Cash change</span><strong>SAR {{ \App\Services\Pay::money(max(0,$sale->paid_cents-$sale->total_cents)) }}</strong></div></div><div class="receipt-totals"><div><span>Subtotal</span><strong>SAR {{ \App\Services\Pay::money($sale->subtotal_cents ?: $sale->total_cents) }}</strong></div><div><span>Discount</span><strong>− SAR {{ \App\Services\Pay::money($sale->discount_cents) }}</strong></div><div><span>Taxable amount</span><strong>SAR {{ \App\Services\Pay::money($sale->taxable_cents) }}</strong></div><div><span>VAT ({{ number_format($sale->tax_rate_units/100,2) }}%)</span><strong>SAR {{ \App\Services\Pay::money($sale->tax_cents) }}</strong></div><div class="grand-total"><span>Total including VAT</span><strong>SAR {{ \App\Services\Pay::money($sale->total_cents) }}</strong></div></div></section>
<section class="receipt-signatures"><div><span>Prepared by</span><strong>{{ $sale->creator->name }}</strong></div><div><span>Customer acknowledgement</span><strong>Signature</strong></div><div class="receipt-paid"><span>Payment</span><strong>RECEIVED</strong></div></section>
<footer class="receipt-footer"><strong>{{ $receiptSettings->footer_text ?: 'Thank you for your business.' }}</strong><span>@if($receiptSettings->address){{ $receiptSettings->address }}@endif @if($receiptSettings->city) · {{ $receiptSettings->city }}@endif @if($receiptSettings->postal_code) {{ $receiptSettings->postal_code }}@endif @if($receiptSettings->phone) · {{ $receiptSettings->phone }}@endif @if($receiptSettings->email) · {{ $receiptSettings->email }}@endif @if($receiptSettings->website) · {{ $receiptSettings->website }}@endif</span><small>Reference SALE-{{ $sale->id }} · Printed {{ now()->format('d M Y h:i A') }}</small></footer>
</article>
<link rel="stylesheet" href="{{ asset('css/safety-shop/sales/sales.css') }}">
<script src="{{ asset('js/safety-shop/sales/checkout.js') }}" defer></script>
@endsection
