@extends('layouts.app')
@section('title','Customer directory')
@section('eyebrow','Invoice module · Customer master')
@section('description','Search and maintain the customers used on standard and simplified invoices.')
@section('actions')<a class="btn secondary" href="{{ route('invoicing.index') }}">← Invoices</a><a class="btn" href="{{ route('invoicing.create') }}">+ New invoice</a>@endsection
@section('content')
@if(auth()->user()->canApprove())
<div class="card"><div class="card-head"><h2>Add customer</h2><span class="badge">Admin entry</span></div><div class="card-body"><form method="POST" action="{{ route('invoicing.customers.store') }}">@csrf<div class="form-grid"><div class="field"><label>Name *</label><input name="name" required value="{{ old('name') }}"></div><div class="field"><label>Arabic name</label><input name="name_ar" value="{{ old('name_ar') }}" dir="rtl"></div><div class="field"><label>Customer type *</label><select name="customer_type"><option value="business" {{ old('customer_type')==='business'?'selected':'' }}>Business B2B</option><option value="consumer" {{ old('customer_type')==='consumer'?'selected':'' }}>Consumer B2C</option></select></div><div class="field"><label>VAT number</label><input name="vat_number" maxlength="15" value="{{ old('vat_number') }}"></div><div class="field"><label>Commercial registration</label><input name="commercial_registration" value="{{ old('commercial_registration') }}"></div><div class="field"><label>Email</label><input name="email" type="email" value="{{ old('email') }}"></div><div class="field"><label>Phone</label><input name="phone" value="{{ old('phone') }}"></div><div class="field"><label>Address *</label><input name="address" required value="{{ old('address') }}"></div><div class="field"><label>City *</label><input name="city" required value="{{ old('city') }}"></div><div class="field"><label>Postal code</label><input name="postal_code" value="{{ old('postal_code') }}"></div><div class="field"><label>Country *</label><input name="country_code" value="{{ old('country_code','SA') }}" maxlength="2" required></div></div><div class="form-footer"><button class="btn">Add customer</button></div></form></div></div>
@endif
<div class="card"><form class="filters" method="GET"><div class="field search"><label>Search customers</label><input name="search" value="{{ request('search') }}" placeholder="Name, VAT, CR, or email"></div><div class="field"><label>Type</label><select name="type"><option value="">All types</option><option value="business" {{ request('type')==='business'?'selected':'' }}>Business B2B</option><option value="consumer" {{ request('type')==='consumer'?'selected':'' }}>Consumer B2C</option></select></div><div class="field"><label>Status</label><select name="status"><option value="">All statuses</option><option value="active" {{ request('status')==='active'?'selected':'' }}>Active</option><option value="inactive" {{ request('status')==='inactive'?'selected':'' }}>Inactive</option></select></div><button class="btn secondary">Filter</button><a class="btn link" href="{{ route('invoicing.customers.index') }}">Clear filters</a></form>
<div class="card-head"><h2>Customers</h2><span class="badge">{{ $customers->total() }} records</span></div><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Type</th><th>VAT / CR</th><th>Contact</th><th>Location</th><th>Invoices</th><th>Status</th>@if(auth()->user()->canApprove())<th></th>@endif</tr></thead><tbody>@forelse($customers as $customer)<tr><td><strong>{{ $customer->name }}</strong><span class="sub">{{ $customer->name_ar ?: '—' }}</span></td><td>{{ $customer->customer_type==='business'?'Business B2B':'Consumer B2C' }}</td><td>{{ $customer->vat_number ?: '—' }}<span class="sub">CR: {{ $customer->commercial_registration ?: '—' }}</span></td><td>{{ $customer->email ?: '—' }}<span class="sub">{{ $customer->phone ?: 'No phone' }}</span></td><td>{{ $customer->city }}, {{ $customer->country_code }}<span class="sub">{{ $customer->address }}</span></td><td>{{ $customer->invoices_count }}</td><td><span class="badge {{ $customer->is_active?'approved':'cancelled' }}">{{ $customer->is_active?'Active':'Inactive' }}</span></td>@if(auth()->user()->canApprove())<td><a class="btn secondary small" href="{{ route('invoicing.customers.edit',$customer) }}">Edit</a></td>@endif</tr>@empty<tr><td colspan="{{ auth()->user()->canApprove()?8:7 }}"><div class="empty"><strong>No customers found</strong><p>Change or clear the directory filters.</p></div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['items'=>$customers])</div>
@endsection
