@extends('layouts.app')
@section('title','Invoice design studio')
@section('eyebrow','Super Admin · Complete invoice branding')
@section('description','Customize invoice header, typography, colors, sections, footer and document elements.')
@section('actions')<a class="btn secondary" href="{{ route('invoicing.index') }}">← Invoice directory</a>@endsection
@section('content')
<div class="notice info"><strong>Super Admin control:</strong> Design changes affect new PDFs and reprints. Financial calculations remain protected.</div>
<form method="POST" action="{{ route('invoicing.design.update') }}" enctype="multipart/form-data">@csrf @method('PUT')
<div class="grid-2"><div class="card"><div class="card-head"><h2>Header and branding</h2></div><div class="card-body"><div class="form-grid"><div class="field full"><label>Company logo</label><input type="file" name="logo" accept=".jpg,.jpeg,.png,.webp"><span class="help">PNG, JPG or WebP; maximum 2 MB.</span></div>@if($settings->logo_path)<div class="field full"><label><input type="checkbox" name="remove_logo" value="1"> Remove current logo</label></div>@endif<div class="field"><label>Header layout *</label><select name="design_header_layout"><option value="split" {{ $settings->design_header_layout==='split'?'selected':'' }}>English / Arabic split</option><option value="centered" {{ $settings->design_header_layout==='centered'?'selected':'' }}>Centered branding</option><option value="logo_left" {{ $settings->design_header_layout==='logo_left'?'selected':'' }}>Logo left</option><option value="blank" {{ $settings->design_header_layout==='blank'?'selected':'' }}>Blank / no company header</option></select><span class="help">Blank hides the logo, company names and CR header. The invoice title remains visible.</span></div><div class="field"><label>Logo width *</label><input type="number" name="design_logo_width" min="30" max="120" value="{{ $settings->design_logo_width }}"></div><div class="field"><label>English title *</label><input name="invoice_title" required maxlength="80" value="{{ $settings->invoice_title }}"></div><div class="field"><label>Arabic title *</label><input name="invoice_title_ar" required maxlength="80" dir="rtl" value="{{ $settings->invoice_title_ar }}"></div><div class="field"><label>Title alignment *</label><select name="design_title_alignment">@foreach(['left','center','right'] as $alignment)<option value="{{ $alignment }}" {{ $settings->design_title_alignment===$alignment?'selected':'' }}>{{ ucfirst($alignment) }}</option>@endforeach</select></div><div class="field"><label>Base font size *</label><input type="number" name="design_font_size" min="6" max="11" step="0.1" value="{{ $settings->design_font_size }}"></div><div class="field"><label>Table density *</label><select name="design_density"><option value="compact" {{ $settings->design_density==='compact'?'selected':'' }}>Compact</option><option value="comfortable" {{ $settings->design_density==='comfortable'?'selected':'' }}>Comfortable</option></select></div></div></div></div>
<div class="card"><div class="card-head"><h2>Colors and visible elements</h2></div><div class="card-body"><div class="form-grid"><div class="field"><label>Primary color *</label><input type="color" name="design_primary_color" value="{{ $settings->design_primary_color }}"></div><div class="field"><label>Text color *</label><input type="color" name="design_text_color" value="{{ $settings->design_text_color }}"></div><div class="field"><label>Section background *</label><input type="color" name="design_header_bg" value="{{ $settings->design_header_bg }}"></div><div class="field"><label>Border color *</label><input type="color" name="design_border_color" value="{{ $settings->design_border_color }}"></div><div class="field full"><label>Custom footer</label><textarea name="invoice_footer" maxlength="500">{{ $settings->invoice_footer }}</textarea></div></div><div class="field"><label>Visible invoice elements</label><div class="grid-2">@foreach(['show_company_cr'=>'CR in header','show_seller_details'=>'Seller details','show_customer_details'=>'Customer details','show_references'=>'Dates and references','show_amount_words'=>'Amount in words','show_notes'=>'Invoice notes','show_bank_details'=>'Bank details','show_signatures'=>'Signature boxes','show_qr'=>'QR code','show_footer_uuid'=>'UUID in footer'] as $field=>$label)<label><input type="checkbox" name="{{ $field }}" value="1" {{ $settings->$field?'checked':'' }}> {{ $label }}</label>@endforeach</div></div></div></div></div>
<div class="card"><div class="card-head"><h2>Style preview</h2><span class="badge">Preview</span></div><div class="card-body"><div style="border:1px solid {{ $settings->design_border_color }};padding:18px;color:{{ $settings->design_text_color }}"><div style="border-bottom:3px solid {{ $settings->design_primary_color }};padding-bottom:10px"><strong>{{ $settings->legal_name }}</strong><span style="float:right" dir="rtl">{{ $settings->legal_name_ar }}</span></div><h2 style="text-align:{{ $settings->design_title_alignment }};color:{{ $settings->design_primary_color }}">{{ $settings->invoice_title }} / {{ $settings->invoice_title_ar }}</h2><div style="background:{{ $settings->design_header_bg }};color:{{ $settings->design_primary_color }};padding:8px;font-weight:bold">Customer Details / تفاصيل العميل</div></div><div class="form-footer"><button class="btn">Save complete invoice design</button></div></div></div>
</form>
@endsection
