@extends('layouts.app')
@section('title','Invoice system')
@section('eyebrow','Saudi invoice platform')
@section('description','Create, approve, print and track professional customer invoices.')
@section('actions')<a class="btn secondary" href="{{ route('invoicing.customers.index') }}">Customers</a><a class="btn" href="{{ route('invoicing.create') }}">+ New invoice</a>@endsection
@section('content')
<div class="notice info"><strong>Independent invoicing:</strong> Invoice operations and QR generation are active. ZATCA connectivity remains isolated in its own module.</div>
<div class="stats"><div class="stat"><div class="label">Drafts</div><div class="value">{{ $stats['draft'] }}</div><div class="note">Awaiting approval</div></div><div class="stat"><div class="label">Approved</div><div class="value">{{ $stats['approved'] }}</div><div class="note">Ready to print</div></div><div class="stat"><div class="label">Paid</div><div class="value">{{ $stats['paid'] }}</div><div class="note">Payment recorded</div></div><div class="stat accent"><div class="label">Approved value · SAR</div><div class="value">{{ \App\Services\Pay::money($stats['total']) }}</div><div class="note">Includes VAT</div></div></div>
<div class="card"><form class="filters" method="GET"><div class="field search"><label>Search</label><input name="search" value="{{ request('search') }}" placeholder="Invoice, customer, or VAT number"></div><div class="field"><label>Status</label><select name="status"><option value="">All statuses</option>@foreach(['draft','approved','paid','cancelled'] as $status)<option value="{{ $status }}" {{ request('status')===$status?'selected':'' }}>{{ ucfirst($status) }}</option>@endforeach</select></div><div class="field"><label>Type</label><select name="type"><option value="">All types</option><option value="standard" {{ request('type')==='standard'?'selected':'' }}>Standard B2B</option><option value="simplified" {{ request('type')==='simplified'?'selected':'' }}>Simplified B2C</option></select></div><button class="btn secondary">Filter</button><a class="btn link" href="{{ route('invoicing.index') }}">Clear filters</a></form>
<div class="table-wrap"><table><thead><tr><th>Invoice</th><th>Customer</th><th>Issue date</th><th>Type</th><th>VAT</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>@forelse($invoices as $invoice)<tr><td><strong>{{ $invoice->invoice_number ?: 'Draft' }}</strong><span class="sub">{{ Str::limit($invoice->uuid,18) }}</span></td><td>{{ $invoice->customer->name }}<span class="sub">{{ $invoice->customer->vat_number ?: 'Consumer' }}</span></td><td>{{ $invoice->issue_date->format('d M Y') }}</td><td>{{ $invoice->invoice_type==='standard'?'B2B Standard':'B2C Simplified' }}<span class="sub">{{ str_replace('_',' ',ucfirst($invoice->document_type)) }}</span></td><td>SAR {{ \App\Services\Pay::money($invoice->tax_cents) }}</td><td><strong>SAR {{ \App\Services\Pay::money($invoice->total_cents) }}</strong></td><td><span class="badge {{ $invoice->status }}">{{ ucfirst($invoice->status) }}</span></td><td><a class="btn secondary small" href="{{ route('invoicing.show',$invoice) }}">Open →</a></td></tr>@empty<tr><td colspan="8"><div class="empty"><strong>No invoices yet</strong><p>Create the first customer invoice.</p><a class="btn" href="{{ route('invoicing.create') }}">Create invoice</a></div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['items'=>$invoices])</div>
@endsection
