@extends('layouts.app')
@section('title','Products & services')
@section('eyebrow','Invoice module · Item master')
@section('description','Maintain reusable products, services, unit prices, and tax categories.')
@section('actions')<a class="btn secondary" href="{{ route('invoicing.index') }}">← Invoices</a><a class="btn" href="{{ route('invoicing.create') }}">+ New invoice</a>@endsection
@section('content')
@if(auth()->user()->canApprove())
<div class="card"><div class="card-head"><h2>Add product or service</h2><span class="badge">Admin entry</span></div><div class="card-body"><form method="POST" action="{{ route('invoicing.items.store') }}">@csrf<div class="form-grid"><div class="field"><label>SKU *</label><input name="sku" required value="{{ old('sku') }}"></div><div class="field"><label>Name *</label><input name="name" required value="{{ old('name') }}"></div><div class="field"><label>Arabic name</label><input name="name_ar" value="{{ old('name_ar') }}" dir="rtl"></div><div class="field"><label>Unit *</label><select name="unit_code"><option value="PCE">Piece</option><option value="HUR">Hour</option><option value="MON">Month</option><option value="DAY">Day</option></select></div><div class="field"><label>Unit price (SAR) *</label><input name="unit_price" type="number" step="0.01" min="0" required value="{{ old('unit_price') }}"></div><div class="field"><label>Tax category *</label><select name="tax_category"><option value="standard">15% Standard</option><option value="zero">0% Zero-rated</option><option value="exempt">Exempt</option></select></div></div><div class="form-footer"><button class="btn">Add product/service</button></div></form></div></div>
@endif
<div class="card"><form class="filters" method="GET"><div class="field search"><label>Search products & services</label><input name="search" value="{{ request('search') }}" placeholder="SKU or description"></div><div class="field"><label>Tax</label><select name="tax"><option value="">All tax categories</option><option value="standard" {{ request('tax')==='standard'?'selected':'' }}>15% Standard</option><option value="zero" {{ request('tax')==='zero'?'selected':'' }}>0% Zero-rated</option><option value="exempt" {{ request('tax')==='exempt'?'selected':'' }}>Exempt</option></select></div><div class="field"><label>Status</label><select name="status"><option value="">All statuses</option><option value="active" {{ request('status')==='active'?'selected':'' }}>Active</option><option value="inactive" {{ request('status')==='inactive'?'selected':'' }}>Inactive</option></select></div><button class="btn secondary">Filter</button><a class="btn link" href="{{ route('invoicing.items.index') }}">Clear filters</a></form>
<div class="card-head"><h2>Products and services</h2><span class="badge">{{ $items->total() }} records</span></div><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Description</th><th>Unit</th><th>Unit price</th><th>Tax category</th><th>Status</th></tr></thead><tbody>@forelse($items as $item)<tr><td><strong>{{ $item->sku }}</strong></td><td>{{ $item->name }}<span class="sub">{{ $item->name_ar ?: '—' }}</span></td><td>{{ $item->unit_code }}</td><td>SAR {{ \App\Services\Pay::money($item->unit_price_cents) }}</td><td>{{ $item->tax_category==='standard'?'15% Standard':($item->tax_category==='zero'?'0% Zero-rated':'Exempt') }}</td><td><span class="badge {{ $item->is_active?'approved':'cancelled' }}">{{ $item->is_active?'Active':'Inactive' }}</span></td></tr>@empty<tr><td colspan="6"><div class="empty"><strong>No products or services found</strong><p>Change or clear the directory filters.</p></div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination',['items'=>$items])</div>
@endsection
