@extends('layouts.app')
@section('title','Invoice masters')
@section('eyebrow','Independent invoicing module')
@section('description','Demo seller identity, customers, products and tax defaults.')
@section('actions')<a class="btn secondary" href="{{ route('invoicing.index') }}">← Invoices</a>@endsection
@section('content')
<div class="notice info">Live ZATCA environment is locked to <strong>Disabled</strong>. Production credentials are not stored in this showcase.</div>
@if(auth()->user()->canApprove())<div class="card"><div class="card-head"><h2>Demo seller profile</h2><span class="badge pending">Demo mode</span></div><div class="card-body"><form method="POST" action="{{ route('invoicing.settings.update') }}">@csrf @method('PUT')<div class="form-grid"><div class="field"><label>Legal name</label><input name="legal_name" required value="{{ $settings->legal_name }}"></div><div class="field"><label>Arabic legal name</label><input name="legal_name_ar" value="{{ $settings->legal_name_ar }}" dir="rtl"></div><div class="field"><label>VAT number</label><input name="vat_number" required maxlength="15" value="{{ $settings->vat_number }}"></div><div class="field"><label>Commercial registration</label><input name="commercial_registration" required value="{{ $settings->commercial_registration }}"></div><div class="field full"><label>Address</label><input name="address" required value="{{ $settings->address }}"></div><div class="field"><label>City</label><input name="city" required value="{{ $settings->city }}"></div><div class="field"><label>Postal code</label><input name="postal_code" required value="{{ $settings->postal_code }}"></div><div class="field"><label>Country code</label><input name="country_code" required maxlength="2" value="{{ $settings->country_code }}"></div><div class="field"><label>Invoice prefix</label><input name="invoice_prefix" required value="{{ $settings->invoice_prefix }}"></div></div><div class="form-footer"><button class="btn">Save seller profile</button></div></form></div></div>@endif
<div class="grid-2">@if(auth()->user()->canApprove())<div class="card"><div class="card-head"><h2>Add customer</h2></div><div class="card-body"><form method="POST" action="{{ route('invoicing.customers.store') }}">@csrf<div class="form-grid"><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Arabic name</label><input name="name_ar" dir="rtl"></div><div class="field"><label>Type</label><select name="customer_type"><option value="business">Business B2B</option><option value="consumer">Consumer B2C</option></select></div><div class="field"><label>VAT number</label><input name="vat_number" maxlength="15"></div><div class="field"><label>Commercial registration</label><input name="commercial_registration"></div><div class="field"><label>Email</label><input name="email" type="email"></div><div class="field"><label>Phone</label><input name="phone"></div><div class="field"><label>Address</label><input name="address" required></div><div class="field"><label>City</label><input name="city" required></div><div class="field"><label>Postal code</label><input name="postal_code"></div><div class="field"><label>Country</label><input name="country_code" value="SA" maxlength="2" required></div></div><div class="form-footer"><button class="btn">Add customer</button></div></form></div></div>
<div class="card"><div class="card-head"><h2>Add product/service</h2></div><div class="card-body"><form method="POST" action="{{ route('invoicing.items.store') }}">@csrf<div class="form-grid"><div class="field"><label>SKU</label><input name="sku" required></div><div class="field"><label>Name</label><input name="name" required></div><div class="field"><label>Arabic name</label><input name="name_ar" dir="rtl"></div><div class="field"><label>Unit code</label><select name="unit_code"><option value="PCE">Piece</option><option value="HUR">Hour</option><option value="MON">Month</option><option value="DAY">Day</option></select></div><div class="field"><label>Unit price SAR</label><input name="unit_price" type="number" step="0.01" min="0" required></div><div class="field"><label>Tax category</label><select name="tax_category"><option value="standard">15% Standard</option><option value="zero">0% Zero</option><option value="exempt">Exempt</option></select></div></div><div class="form-footer"><button class="btn">Add product/service</button></div></form></div></div>@endif</div>
<div class="card"><div class="card-head"><h2>Customer directory</h2><span class="badge">{{ $customers->total() }}</span></div><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Type</th><th>VAT/CR</th><th>Contact</th><th>Location</th></tr></thead><tbody>@foreach($customers as $customer)<tr><td><strong>{{ $customer->name }}</strong><span class="sub">{{ $customer->name_ar }}</span></td><td>{{ ucfirst($customer->customer_type) }}</td><td>{{ $customer->vat_number ?: '—' }}<span class="sub">{{ $customer->commercial_registration }}</span></td><td>{{ $customer->email ?: '—' }}<span class="sub">{{ $customer->phone }}</span></td><td>{{ $customer->city }}, {{ $customer->country_code }}</td></tr>@endforeach</tbody></table></div>@include('partials.pagination',['items'=>$customers])</div>
<div class="card"><div class="card-head"><h2>Products and services</h2><span class="badge">{{ $items->total() }}</span></div><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Description</th><th>Unit</th><th>Price SAR</th><th>Tax</th></tr></thead><tbody>@foreach($items as $item)<tr><td><strong>{{ $item->sku }}</strong></td><td>{{ $item->name }}<span class="sub">{{ $item->name_ar }}</span></td><td>{{ $item->unit_code }}</td><td>{{ \App\Services\Pay::money($item->unit_price_cents) }}</td><td>{{ $item->tax_category==='standard'?'15% Standard':ucfirst($item->tax_category) }}</td></tr>@endforeach</tbody></table></div>@include('partials.pagination',['items'=>$items])</div>
@endsection
