@extends('layouts.app')
@section('title','Invoice settings')
@section('eyebrow','Invoice module · Seller profile')
@section('description','Seller identity and numbering used by the normal invoice platform.')
@section('actions')<a class="btn secondary" href="{{ route('invoicing.index') }}">← Invoices</a>@endsection
@section('content')
<div class="notice info"><strong>Invoice configuration:</strong> ZATCA onboarding and credentials are managed separately in the ZATCA Integration Center.</div>
<div class="stats"><div class="stat"><div class="label">Currency</div><div class="value" style="font-size:1.3rem">Saudi Riyal</div><div class="note">SAR</div></div><div class="stat"><div class="label">Standard VAT</div><div class="value" style="font-size:1.3rem">15%</div><div class="note">Item-level calculation</div></div><div class="stat"><div class="label">Next invoice number</div><div class="value" style="font-size:1.3rem">{{ $settings->invoice_prefix }}-{{ now()->format('Y') }}-{{ str_pad($settings->next_number,6,'0',STR_PAD_LEFT) }}</div><div class="note">Assigned after approval</div></div></div>
<div class="card"><div class="card-head"><h2>Seller profile</h2><span class="badge approved">Active</span></div><div class="card-body">
@if(auth()->user()->canApprove())<form method="POST" action="{{ route('invoicing.settings.update') }}">@csrf @method('PUT')<div class="form-grid"><div class="field"><label>Legal name *</label><input name="legal_name" required value="{{ $settings->legal_name }}"></div><div class="field"><label>Arabic legal name</label><input name="legal_name_ar" value="{{ $settings->legal_name_ar }}" dir="rtl"></div><div class="field"><label>VAT number *</label><input name="vat_number" required maxlength="15" value="{{ $settings->vat_number }}"></div><div class="field"><label>Commercial registration *</label><input name="commercial_registration" required value="{{ $settings->commercial_registration }}"></div><div class="field full"><label>Address *</label><input name="address" required value="{{ $settings->address }}"></div><div class="field"><label>City *</label><input name="city" required value="{{ $settings->city }}"></div><div class="field"><label>Postal code *</label><input name="postal_code" required value="{{ $settings->postal_code }}"></div><div class="field"><label>Country code *</label><input name="country_code" required maxlength="2" value="{{ $settings->country_code }}"></div><div class="field"><label>Invoice prefix *</label><input name="invoice_prefix" required value="{{ $settings->invoice_prefix }}"></div><div class="field"><label>Bank name</label><input name="bank_name" value="{{ $settings->bank_name }}"></div><div class="field"><label>Account name</label><input name="bank_account_name" value="{{ $settings->bank_account_name }}"></div><div class="field"><label>Account number</label><input name="bank_account_number" value="{{ $settings->bank_account_number }}"></div><div class="field"><label>IBAN</label><input name="iban" maxlength="34" value="{{ $settings->iban }}"></div><div class="field"><label>Bank branch</label><input name="bank_branch" value="{{ $settings->bank_branch }}"></div></div><div class="form-footer"><button class="btn">Save seller profile</button></div></form>
@else<div class="form-grid"><div class="field"><label>Legal name</label><input readonly value="{{ $settings->legal_name }}"></div><div class="field"><label>VAT number</label><input readonly value="{{ $settings->vat_number }}"></div><div class="field"><label>Commercial registration</label><input readonly value="{{ $settings->commercial_registration }}"></div><div class="field"><label>Registered address</label><input readonly value="{{ $settings->address }}, {{ $settings->city }} {{ $settings->postal_code }}"></div></div><div class="notice info">Settings are read-only for managers. An admin or super admin can update the seller profile.</div>@endif
</div></div>
@endsection
