@extends('layouts.app')
@section('title',$invoice->invoice_number ?: 'Invoice draft')
@section('eyebrow','Invoice system · '.ucfirst($invoice->status))
@section('description',$invoice->customer->name.' · '.$invoice->issue_date->format('d F Y'))
@section('actions')<a class="btn secondary" href="{{ route('invoicing.index') }}">← Directory</a>@if($invoice->status!=='draft')<a class="btn secondary" href="{{ route('invoicing.xml',$invoice) }}">Download XML</a><a class="btn" href="{{ route('invoicing.pdf',$invoice) }}">Download PDF</a>@endif @endsection
@section('content')
<div class="notice info"><strong>Invoice platform:</strong> This invoice follows the internal approval workflow. ZATCA submission, when activated later, is managed separately.</div>
<div class="columns"><div><div class="card payslip-card"><div class="card-head"><div><div class="eyebrow">{{ $invoice->invoice_type==='standard'?'Standard B2B':'Simplified B2C' }}</div><h2>{{ ucwords(str_replace('_',' ',$invoice->document_type)) }}</h2></div><span class="badge {{ $invoice->status }}">{{ ucfirst($invoice->status) }}</span></div><div class="card-body"><div class="grid-2"><dl class="detail-list"><div><dt>Supplier</dt><dd>{{ $settings->legal_name }}<span class="sub">VAT {{ $settings->vat_number }}</span></dd></div><div><dt>Customer</dt><dd>{{ $invoice->customer->name }}<span class="sub">{{ $invoice->customer->vat_number ? 'VAT '.$invoice->customer->vat_number : 'Consumer' }}</span></dd></div></dl><dl class="detail-list"><div><dt>Invoice number</dt><dd>{{ $invoice->invoice_number ?: 'Assigned after approval' }}</dd></div><div><dt>UUID</dt><dd>{{ $invoice->uuid }}</dd></div></dl></div>
<div class="table-wrap" style="margin:22px -23px 0"><table><thead><tr><th>Description</th><th>Quantity</th><th>Unit price</th><th>Discount</th><th>VAT</th><th>Total</th></tr></thead><tbody>@foreach($invoice->lines as $line)<tr><td><strong>{{ $line->description }}</strong><span class="sub">{{ strtoupper($line->tax_category) }} · {{ \App\Services\Pay::decimal($line->tax_rate_units) }}%</span></td><td>{{ \App\Services\Pay::decimal($line->quantity_units) }} {{ $line->unit_code }}</td><td>{{ \App\Services\Pay::money($line->unit_price_cents) }}</td><td>{{ \App\Services\Pay::money($line->discount_cents) }}</td><td>{{ \App\Services\Pay::money($line->tax_cents) }}</td><td><strong>{{ \App\Services\Pay::money($line->line_total_cents) }}</strong></td></tr>@endforeach</tbody></table></div>
<div class="salary-row"><span>Subtotal</span><strong>SAR {{ \App\Services\Pay::money($invoice->subtotal_cents) }}</strong></div><div class="salary-row"><span>Discount</span><strong>− SAR {{ \App\Services\Pay::money($invoice->discount_cents) }}</strong></div><div class="salary-row"><span>VAT</span><strong>SAR {{ \App\Services\Pay::money($invoice->tax_cents) }}</strong></div><div class="salary-total"><span>Total including VAT</span><strong>SAR {{ \App\Services\Pay::money($invoice->total_cents) }}</strong></div>
@if($invoice->notes)<div class="experience-text" style="margin-top:18px">{{ $invoice->notes }}</div>@endif</div></div></div>
<div><div class="card"><div class="card-head"><h2>Invoice workflow</h2><span class="badge {{ $invoice->status }}">{{ ucfirst($invoice->status) }}</span></div><div class="card-body"><p class="help">Approval permanently assigns the next invoice number and enables PDF/XML export.</p>@if($invoice->status==='draft' && auth()->user()->canApprove())<form method="POST" action="{{ route('invoicing.approve',$invoice) }}" data-confirm="Approve and permanently number this invoice?">@csrf<button class="btn" style="width:100%">Approve invoice</button></form>@elseif($invoice->status==='approved' && auth()->user()->canApprove())<form method="POST" action="{{ route('invoicing.paid',$invoice) }}">@csrf<button class="btn" style="width:100%">Mark paid</button></form>@endif @if($invoice->status==='draft' && auth()->user()->isSuperAdmin())<form method="POST" action="{{ route('invoicing.destroy',$invoice) }}" data-confirm="Delete this draft?" style="margin-top:10px">@csrf @method('DELETE')<button class="btn danger" style="width:100%">Delete draft</button></form>@endif</div></div>
<div class="card"><div class="card-head"><h2>Invoice QR code</h2><span class="badge approved">Active</span></div><div class="card-body" style="text-align:center"><img src="{{ $qr }}" alt="Invoice QR code" width="180" height="180"><div class="field" style="text-align:left"><label>Encoded invoice details</label><textarea readonly>{{ $qrPayload }}</textarea></div><p class="help">Scan to read the invoice number, supplier, customer, date, VAT, total and UUID.</p></div></div>
<div class="card"><div class="card-head"><h2>Activity</h2></div><div class="card-body">@foreach($invoice->events as $event)<div class="company-row"><div><strong>{{ $event->event }}</strong><small>{{ $event->details }}</small></div><small>{{ $event->created_at->format('d M Y H:i') }}<br>{{ optional($event->user)->name }}</small></div>@endforeach</div></div></div></div>
@endsection
