@extends('layouts.app')
@section('title', $workforce === 'own' ? 'Own employee monthly salaries' : 'Rental payroll')
@section('eyebrow', $workforce === 'own' ? 'Own employees · Monthly salaries' : 'Rental manpower · Hourly payroll')
@section('description', 'Generated salaries remain pending until Admin approval.')
@section('actions')<a class="btn secondary" href="{{ route($routePrefix.'.export', ['month' => $month]) }}">↓ Export CSV</a>@endsection
@section('content')
<div class="grid-2"><a class="stat stat-link" href="#payroll-directory"><div class="label">Filtered net salary · SAR</div><div class="value">{{ \App\Services\Pay::money($total) }}</div><div class="note">{{ $payrolls->total() }} records for {{ $month }} · Open salaries →</div></a><div class="card"><div class="card-body"><h3>Pending approval workflow</h3><p class="description">Generate salary after hours approval. Admin approves the salary; Super Admin can perform every action.</p></div></div></div>
@if(auth()->user()->role !== 'admin')<div class="card"><div class="card-head"><h2>Generate {{ $workforce === 'own' ? 'monthly salary' : 'rental salary' }}</h2></div><div class="card-body"><form method="POST" action="{{ route($routePrefix.'.store') }}">@csrf<div class="form-grid"><div class="field"><label>Employee *</label><select name="employee_id" required><option value="">Select employee</option>@foreach($employees as $employee)<option value="{{ $employee->id }}">{{ $employee->name }} · {{ $employee->company->name }}</option>@endforeach</select></div><div class="field"><label>Salary month *</label><input type="month" name="month" required max="{{ now()->format('Y-m') }}" value="{{ old('month', $month) }}"></div><div class="field"><label>Allowances (SAR)</label><input name="allowance" type="number" min="0" step="0.01" required value="{{ old('allowance', '0.00') }}"></div><div class="field"><label>Deductions (SAR)</label><input name="deduction" type="number" min="0" step="0.01" required value="{{ old('deduction', '0.00') }}"></div><div class="field full"><label>Notes</label><input name="notes" maxlength="2000" value="{{ old('notes') }}"></div></div><div class="form-footer"><button class="btn">Generate pending salary →</button></div></form></div></div>@endif
<div class="card"><form class="filters" method="GET">@if($workforce === 'rental')<div class="field search"><label for="payroll_search">Search payroll</label><input id="payroll_search" type="search" name="search" value="{{ request('search') }}" maxlength="100" placeholder="Employee, Iqama, company or designation"></div>@endif<div class="field"><label>Month</label><input type="month" name="month" value="{{ $month }}"></div><div class="field"><label>Company</label><select name="company_id"><option value="">All companies</option>@foreach($companies as $company)<option value="{{ $company->id }}" {{ request('company_id') == $company->id ? 'selected' : '' }}>{{ $company->name }}</option>@endforeach</select></div><div class="field"><label>Status</label><select name="status"><option value="">All statuses</option>@foreach(['pending','approved','paid'] as $status)<option value="{{ $status }}" {{ request('status') === $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>@endforeach</select></div><button class="btn secondary">Filter</button><a href="{{ route($routePrefix.'.index') }}" class="btn link">Clear filters</a></form>
<div class="table-wrap"><table><thead><tr><th>Employee</th>@if($workforce === 'rental')<th>Rental hour rate</th><th>Regular hours</th><th>Overtime hours</th>@endif<th>Base pay</th><th>Overtime pay</th><th>Net salary</th><th>Status</th><th></th></tr></thead><tbody>@forelse($payrolls as $payroll)<tr><td><strong>{{ $payroll->employee_name }}</strong><span class="sub">{{ $payroll->company_name }} · {{ $payroll->designation_name }}</span><span class="sub">{{ $payroll->iqama_number }} · {{ $payroll->month }}</span></td>@if($workforce === 'rental')<td>@if($payroll->regular_units > 0)<strong>SAR {{ \App\Services\Pay::money((int) round($payroll->regular_pay_cents * 100 / $payroll->regular_units)) }}</strong><span class="sub">effective approved rate</span>@else<span class="muted">—</span>@endif</td><td>{{ \App\Services\Pay::decimal($payroll->regular_units) }}</td><td>{{ \App\Services\Pay::decimal($payroll->overtime_units) }}</td>@endif<td>{{ \App\Services\Pay::money($payroll->regular_pay_cents) }}</td><td>{{ \App\Services\Pay::money($payroll->overtime_pay_cents) }}</td><td><strong>SAR {{ \App\Services\Pay::money($payroll->net_pay_cents) }}</strong></td><td><span class="badge {{ $payroll->status }}">{{ ucfirst($payroll->status) }}</span></td><td><a class="btn secondary small" href="{{ route($routePrefix.'.show', $payroll) }}">Open →</a></td></tr>@empty<tr><td colspan="{{ $workforce === 'rental' ? 9 : 6 }}"><div class="empty">No salary records found.</div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination', ['items'=>$payrolls])</div>
@endsection
