@extends('layouts.app')
@section('title','Salary payslip')
@section('eyebrow',$workforce === 'own' ? 'Own employees · Monthly salary' : 'Rental manpower · Payroll')
@section('actions')<a class="btn secondary" href="{{ route($routePrefix.'.index',['month'=>$payroll->month]) }}">← Salary register</a><a class="btn {{ $payroll->status === 'pending' ? 'secondary' : '' }}" href="{{ route($routePrefix.'.pdf',$payroll) }}">{{ $payroll->status === 'pending' ? '⏳ Print payslip' : '↓ Print payslip' }}</a>@endsection
@section('content')<div class="columns"><div class="card payslip-card"><div class="card-body"><div class="section-title"><div><div class="eyebrow">{{ $payroll->company_name }}</div><h2>{{ $payroll->employee_name }}</h2><span class="help">{{ $payroll->designation_name }} · {{ $payroll->month }}</span></div><span class="badge {{ $payroll->status }}">{{ ucfirst($payroll->status) }}</span></div><div class="salary-row"><span>Base salary</span><strong>SAR {{ \App\Services\Pay::money($payroll->regular_pay_cents) }}</strong></div><div class="salary-row"><span>Overtime</span><strong>SAR {{ \App\Services\Pay::money($payroll->overtime_pay_cents) }}</strong></div><div class="salary-row"><span>Allowances</span><strong>+ {{ \App\Services\Pay::money($payroll->allowance_cents) }}</strong></div><div class="salary-row"><span>Other deductions</span><strong>- {{ \App\Services\Pay::money($payroll->deduction_cents) }}</strong></div><div class="salary-row"><span>Employee advance repayment</span><strong>- {{ \App\Services\Pay::money($payroll->advance_deduction_cents) }}</strong></div><div class="salary-total"><span>Net salary</span><strong>SAR {{ \App\Services\Pay::money($payroll->net_pay_cents) }}</strong></div></div></div>
<div class="no-print">
@if($payroll->status === 'pending')<div class="notice info"><strong>Waiting for approval.</strong> This salary slip cannot be printed until an Admin or Super Admin approves it.</div>@endif
@if($payroll->status === 'pending' && auth()->user()->canApprove())<div class="card"><div class="card-body"><h3>Admin approval</h3><p class="description">Approve this salary before payment can be recorded.</p><form method="POST" action="{{ route($routePrefix.'.approve',$payroll) }}" data-confirm="Approve this salary?">@csrf<button class="btn">✓ Approve salary</button></form></div></div>@endif
@if($payroll->status === 'pending' && auth()->user()->isSuperAdmin())<div class="card"><div class="card-body"><h3>Super Admin controls</h3><form method="POST" action="{{ route($routePrefix.'.destroy',$payroll) }}" data-confirm="Delete this pending salary?">@csrf @method('DELETE')<button class="btn danger">Delete pending salary</button></form></div></div>@endif
@if($payroll->status === 'approved' && auth()->user()->isSuperAdmin())<div class="card"><div class="card-body"><h3>Record payment</h3><form method="POST" action="{{ route($routePrefix.'.paid',$payroll) }}" data-confirm="Confirm payment?">@csrf<button class="btn">✓ Mark paid</button></form></div></div>@endif
</div></div>@endsection
