@extends('layouts.app')
@section('title',($customer->exists?'Edit':'Add').' customer')
@section('eyebrow','Safety shop · Customer master')
@section('description','Customer details are reused during checkout while each receipt keeps its original snapshot.')
@section('actions')<a class="btn secondary" href="{{ route('safety-shop.customers.index') }}">Back to customers</a>@endsection
@section('content')
@include('safety-shop.shared.nav')
<div class="card"><div class="card-body"><form method="POST" action="{{ $customer->exists?route('safety-shop.customers.update',$customer):route('safety-shop.customers.store') }}">@csrf @if($customer->exists)@method('PUT')@endif
<div class="form-grid">
<div class="field"><label for="customer_type">Customer type *</label><select id="customer_type" name="customer_type"><option value="retail" {{ old('customer_type',$customer->customer_type)==='retail'?'selected':'' }}>Retail customer</option><option value="company" {{ old('customer_type',$customer->customer_type)==='company'?'selected':'' }}>Company purchaser</option></select><small>Retail keeps checkout fast. Company enables tax and buyer details.</small></div>
<div class="field"><label for="name"><span data-retail-label>Customer name</span><span data-company-label hidden>Legal company name</span> *</label><input id="name" name="name" required maxlength="150" value="{{ old('name',$customer->name) }}"></div>
<div class="field company-field"><label for="contact_person">Purchaser / contact person *</label><input id="contact_person" name="contact_person" maxlength="150" value="{{ old('contact_person',$customer->contact_person) }}"></div>
<div class="field"><label for="phone">Mobile / phone</label><input id="phone" name="phone" maxlength="30" value="{{ old('phone',$customer->phone) }}" placeholder="+966550000000"><small>Used to match repeat customers.</small></div>
<div class="field"><label for="email">Email</label><input id="email" name="email" type="email" maxlength="150" value="{{ old('email',$customer->email) }}"></div>
<div class="field company-field"><label for="vat_number">VAT number *</label><input id="vat_number" name="vat_number" inputmode="numeric" pattern="[0-9]{15}" maxlength="15" value="{{ old('vat_number',$customer->vat_number) }}" placeholder="15 digits"></div>
<div class="field company-field"><label for="commercial_registration">Commercial registration</label><input id="commercial_registration" name="commercial_registration" maxlength="30" value="{{ old('commercial_registration',$customer->commercial_registration) }}"></div>
<div class="field full"><label for="address">Address / additional details</label><input id="address" name="address" maxlength="500" value="{{ old('address',$customer->address) }}"></div>
<div class="field company-field"><label for="building_number">Building number</label><input id="building_number" name="building_number" maxlength="20" value="{{ old('building_number',$customer->building_number) }}"></div><div class="field company-field"><label for="street">Street</label><input id="street" name="street" maxlength="150" value="{{ old('street',$customer->street) }}"></div><div class="field company-field"><label for="district">District</label><input id="district" name="district" maxlength="100" value="{{ old('district',$customer->district) }}"></div><div class="field company-field"><label for="city">City</label><input id="city" name="city" maxlength="100" value="{{ old('city',$customer->city) }}"></div><div class="field company-field"><label for="postal_code">Postal code</label><input id="postal_code" name="postal_code" maxlength="10" value="{{ old('postal_code',$customer->postal_code) }}"></div><div class="field company-field"><label for="country_code">Country code *</label><input id="country_code" name="country_code" required maxlength="2" value="{{ old('country_code',$customer->country_code ?: 'SA') }}"></div>
<div class="field"><label for="is_active">Status *</label><select id="is_active" name="is_active"><option value="1" {{ old('is_active',$customer->is_active)?'selected':'' }}>Active</option><option value="0" {{ !old('is_active',$customer->is_active)?'selected':'' }}>Inactive</option></select><small>Inactive customers remain in history but are hidden from checkout.</small></div></div>
<div class="form-footer"><button class="btn">Save customer</button><a class="btn secondary" href="{{ route('safety-shop.customers.index') }}">Cancel</a></div></form></div></div>
<script>(()=>{const type=document.getElementById('customer_type');const sync=()=>{const company=type.value==='company';document.querySelectorAll('.company-field').forEach(el=>el.hidden=!company);document.querySelectorAll('[data-company-label]').forEach(el=>el.hidden=!company);document.querySelectorAll('[data-retail-label]').forEach(el=>el.hidden=company);document.getElementById('contact_person').required=company;document.getElementById('vat_number').required=company};type.addEventListener('change',sync);sync()})()</script>
@endsection
