@extends('layouts.app')
@section('title','Customer directory')
@section('eyebrow','Safety shop · Master data')
@section('description','Manage quick retail profiles and complete company purchaser records for repeat sales and tax receipts.')
@section('actions')
@if(auth()->user()->canApprove())<a class="btn" href="{{ route('safety-shop.customers.create') }}">+ Add customer</a>@endif
@endsection
@section('content')
@include('safety-shop.shared.nav')
<div class="card"><form class="filters" method="GET"><div class="field search"><label for="customer-search">Search</label><input id="customer-search" name="search" value="{{ request('search') }}" placeholder="Name, mobile, VAT or CR"></div><div class="field"><label for="customer-type">Customer type</label><select id="customer-type" name="type"><option value="">All customer types</option><option value="retail" {{ request('type')==='retail'?'selected':'' }}>Retail customer</option><option value="company" {{ request('type')==='company'?'selected':'' }}>Company purchaser</option></select></div><div class="field"><label for="customer-approval">Approval</label><select id="customer-approval" name="approval"><option value="">All approvals</option><option value="pending" {{ request('approval')==='pending'?'selected':'' }}>Pending approval</option><option value="approved" {{ request('approval')==='approved'?'selected':'' }}>Approved</option></select></div><div class="field"><label for="customer-status">Status</label><select id="customer-status" name="status"><option value="">All statuses</option><option value="active" {{ request('status')==='active'?'selected':'' }}>Active</option><option value="inactive" {{ request('status')==='inactive'?'selected':'' }}>Inactive</option></select></div><button class="btn secondary">Filter</button><a class="btn link" href="{{ route('safety-shop.customers.index') }}">Clear filters</a></form>
<div class="card-head"><h2>Customer master records</h2><span class="badge">{{ $customers->total() }}</span></div><div class="table-wrap"><table><thead><tr><th>Customer</th><th>Type</th><th>Contact</th><th>Tax identity</th><th>Purchases</th><th>Lifetime sales SAR</th><th>Last purchase</th><th>Status</th><th></th></tr></thead><tbody>
@forelse($customers as $customer)<tr><td><strong>{{ $customer->name }}</strong>@if($customer->contact_person)<span class="sub">Buyer: {{ $customer->contact_person }}</span>@endif</td><td><span class="badge">{{ $customer->customer_type==='company'?'Company purchaser':'Retail customer' }}</span></td><td>{{ $customer->phone ?: '—' }}<span class="sub">{{ $customer->email }}</span><span class="sub">{{ $customer->city ?: $customer->address }}</span></td><td>@if($customer->customer_type==='company')VAT {{ $customer->vat_number ?: '—' }}<span class="sub">CR {{ $customer->commercial_registration ?: '—' }}</span>@else<span class="muted">Not required</span>@endif</td><td>{{ number_format($customer->purchase_count) }}</td><td>{{ \App\Services\Pay::money($customer->lifetime_value_cents) }}</td><td>{{ optional($customer->last_purchase_at)->format('d M Y H:i') ?: '—' }}</td><td><span class="badge {{ $customer->approval_status==='approved'?'approved':'pending' }}">{{ $customer->approval_status==='approved'?'Approved':'Pending approval' }}</span><span class="sub">{{ $customer->is_active?'Active':'Inactive' }}</span></td><td>@if(auth()->user()->canApprove())<a href="{{ route('safety-shop.customers.edit',$customer) }}">Edit</a>@if($customer->approval_status!=='approved')<form method="POST" action="{{ route('safety-shop.customers.approve',$customer) }}" style="display:inline">@csrf<button class="btn link" type="submit">Approve</button></form>@endif @endif</td></tr>@empty<tr><td colspan="9"><div class="empty">No customers found. Checkout customers remain pending until an admin approves them.</div></td></tr>@endforelse
</tbody></table></div>@include('partials.pagination',['items'=>$customers])</div>
@endsection
