@extends('layouts.app')
@section('title', $workforce === 'own' ? 'Attendance & overtime' : 'Rental timesheets')
@section('eyebrow', $workforce === 'own' ? 'Own employees · Attendance' : 'Rental manpower · Hours register')
@section('description', $workforce === 'own' ? 'Record attendance and overtime for your own employees, separately from rental timesheets.' : 'Daily hours, review status, and the entries used to calculate rental salaries.')
@section('actions')<a class="btn secondary" href="{{ route($routePrefix.'.pdf', request()->query()) }}">↓ PDF report</a><a class="btn secondary" href="{{ route($routePrefix.'.bulk') }}">+ Date range</a><a class="btn" href="{{ route($routePrefix.'.create') }}">+ Add {{ $workforce === 'own' ? 'attendance' : 'hours' }}</a>@endsection
@section('content')<div class="stats" style="grid-template-columns:repeat(3,minmax(0,1fr))"><a class="stat stat-link" href="#directory-results"><div class="label">Filtered regular hours</div><div class="value">{{ \App\Services\Pay::decimal($totals['regular']) }}</div><div class="note">All statuses matching your filters · View entries →</div></a><a class="stat stat-link" href="{{ route($routePrefix.'.index', array_merge(request()->query(), ['status' => 'approved'])) }}#directory-results"><div class="label">Filtered overtime hours</div><div class="value">{{ \App\Services\Pay::decimal($totals['overtime']) }}</div><div class="note">Approval required for overtime pay · Approved entries →</div></a><a class="stat stat-link" href="#directory-results"><div class="label">Daily entries</div><div class="value">{{ $timesheets->total() }}</div><div class="note">One record per employee / day · Open list →</div></a></div>
<span id="directory-results"></span>
<div class="card"><form class="filters" method="GET"><div class="field"><label for="month">Month</label><input id="month" type="month" name="month" value="{{ $month }}"></div><div class="field"><label for="company_id">Company</label><select id="company_id" name="company_id"><option value="">All companies</option>@foreach($companies as $company)<option value="{{ $company->id }}" {{ request('company_id') == $company->id ? 'selected' : '' }}>{{ $company->name }}</option>@endforeach</select></div><div class="field search"><label for="employee_search">Employee search</label><input id="employee_search" name="employee_search" value="{{ request('employee_search') }}" maxlength="100" placeholder="Name, Iqama, company or designation"></div><div class="field"><label for="status">Status</label><select id="status" name="status"><option value="">All statuses</option>@foreach(['pending', 'approved', 'rejected'] as $status)<option value="{{ $status }}" {{ request('status') === $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>@endforeach</select></div><button class="btn secondary">Filter</button><a href="{{ route($routePrefix.'.index') }}" class="btn link">Clear filters</a></form>
@if(!request()->filled('employee_id'))
<div class="card-head"><h2>{{ $workforce === 'own' ? 'Employee attendance directory' : 'Rental employee timesheets' }}</h2><span class="badge">{{ $directoryEmployees->total() }} employees</span></div>
<div class="filters" style="padding-top:0"><div class="field search"><label for="employee_live_search">Search employees</label><input id="employee_live_search" type="search" placeholder="Search name, company, or designation..." data-employee-search autocomplete="off"></div><button type="button" class="btn link" data-clear-employee-search>Clear search</button><span class="help" data-employee-search-count>{{ $employeeDirectory->count() }} employees shown</span></div>
<div class="table-wrap"><table><thead><tr><th>Employee</th><th>Company</th><th>Designation</th>@if($workforce === 'rental')<th>Rental hour rate</th>@endif<th>Regular hours / day</th><th>Entries</th><th>Recorded regular hours</th><th>Overtime</th><th>Pending</th><th>Timesheet</th></tr></thead><tbody>
@forelse($employeeDirectory as $row)<tr data-employee-row data-search-text="{{ strtolower($row['employee']->name.' '.$row['employee']->company->name.' '.$row['employee']->designation->name) }}"><td><a href="{{ route($routePrefix.'.index', array_filter(['month' => $month, 'company_id' => request('company_id'), 'employee_id' => $row['employee']->id])) }}"><strong>{{ $row['employee']->name }}</strong></a><span class="sub">Click to open all timesheet statuses</span></td><td>{{ $row['employee']->company->name }}</td><td>{{ $row['employee']->designation->name }}</td>@if($workforce === 'rental')<td><strong>SAR {{ \App\Services\Pay::money($row['employee']->hourly_rate_cents) }}</strong><span class="sub">per rental hour</span></td>@endif<td><strong>{{ \App\Services\Pay::decimal($row['employee']->regular_hours_units ?: 800) }}</strong><span class="sub">employee default</span></td><td>{{ $row['entries'] }}</td><td>{{ \App\Services\Pay::decimal($row['regular']) }}</td><td>{{ \App\Services\Pay::decimal($row['overtime']) }}</td><td>@if($row['pending'])<span class="badge pending">{{ $row['pending'] }} pending</span>@else<span class="badge approved">Clear</span>@endif</td><td><a class="btn secondary small" href="{{ route($routePrefix.'.employee.pdf.form', $row['employee']) }}">Generate timesheet</a></td></tr>
@empty<tr><td colspan="{{ $workforce === 'rental' ? 10 : 9 }}"><div class="empty"><strong>No employees found.</strong><p>Choose another company or add an employee.</p></div></td></tr>@endforelse
</tbody></table></div>
@include('partials.pagination', ['items' => $directoryEmployees])
@else
<div class="card-head"><h2>{{ optional($selectedEmployee)->name }} - {{ \Carbon\Carbon::createFromFormat('!Y-m', $month)->format('F Y') }}</h2><a href="{{ route($routePrefix.'.index', array_filter(['month' => $month, 'status' => request('status'), 'company_id' => request('company_id')])) }}">← All employees</a></div>
@if(auth()->user()->isAdmin())<form id="bulk-approve-form" method="POST" action="{{ route($routePrefix.'.bulk.approve') }}" data-confirm="Approve all selected time entries?">@csrf<div class="form-footer" style="justify-content:flex-start"><button class="btn" data-bulk-approve disabled>✓ Approve selected</button><span class="help" data-bulk-count>Select pending entries below.</span></div></form>@endif
<div class="table-wrap"><table><thead><tr>@if(auth()->user()->isAdmin())<th style="width:42px"><input type="checkbox" data-select-all-pending aria-label="Select all pending entries on this page"></th>@endif<th>Employee / date</th><th>Hours</th><th>Status / notes</th><th>Actions</th></tr></thead><tbody>@forelse($timesheets as $entry)<tr>@if(auth()->user()->isAdmin())<td>@if($entry->status === 'pending' && !$entry->payroll_id)<input type="checkbox" name="timesheet_ids[]" value="{{ $entry->id }}" form="bulk-approve-form" data-pending-entry aria-label="Select {{ $entry->employee->name }} on {{ $entry->work_date->format('d M Y') }}">@endif</td>@endif<td><strong>{{ $entry->employee->name }}</strong><span class="sub">{{ $entry->employee->company->name }}</span><span class="sub">{{ $entry->work_date->format('d M Y') }} · by {{ optional($entry->creator)->name }}</span></td><td><strong>{{ \App\Services\Pay::decimal($entry->regular_units) }} regular</strong><span class="sub">{{ \App\Services\Pay::decimal($entry->overtime_units) }} overtime</span></td><td class="wrap"><span class="badge {{ $entry->status }}">{{ ucfirst($entry->status) }}</span>@if($entry->payroll_id)<span class="badge">Payroll locked</span>@endif @if($entry->notes)<span class="sub">{{ $entry->notes }}</span>@endif @if($entry->review_note)<span class="sub">Review: {{ $entry->review_note }}</span>@endif</td><td>@if($entry->status !== 'approved' && !$entry->payroll_id)<div class="actions">@if(auth()->user()->isSuperAdmin() || (auth()->user()->isCompanyAdmin() && $entry->status === 'pending'))<a class="btn secondary small" href="{{ route($routePrefix.'.edit', $entry) }}">Edit hours</a>@endif @if(auth()->user()->isSuperAdmin() || (auth()->user()->isCompanyAdmin() && $entry->status === 'pending'))<form method="POST" action="{{ route($routePrefix.'.destroy', $entry) }}" data-confirm="Delete this hours entry?">@csrf @method('DELETE')<button class="btn danger small">Delete</button></form>@endif</div>@endif
@if(auth()->user()->isAdmin() && $entry->status === 'pending' && !$entry->payroll_id)<div class="actions" style="margin-top:8px"><form method="POST" action="{{ route($routePrefix.'.review', $entry) }}">@csrf<input type="hidden" name="status" value="approved"><button class="btn small">✓ Approve</button></form><details><summary style="font-size:11px;cursor:pointer;color:#a54742">Reject</summary><form class="review-form" method="POST" action="{{ route($routePrefix.'.review', $entry) }}" style="margin-top:6px">@csrf<input type="hidden" name="status" value="rejected"><input name="review_note" required maxlength="1000" placeholder="Reason for rejection" aria-label="Rejection reason"><button class="btn danger small">Reject</button></form></details></div>@endif
@if(auth()->user()->isSuperAdmin() && $entry->status === 'approved' && !$entry->payroll_id)<details style="margin-top:8px"><summary style="font-size:11px;cursor:pointer">Reopen for correction</summary><form class="review-form" method="POST" action="{{ route($routePrefix.'.review', $entry) }}">@csrf<input type="hidden" name="status" value="pending"><input name="review_note" required maxlength="1000" placeholder="Reason for reopening" aria-label="Reopening reason"><button class="btn secondary small">Reopen</button></form></details>@endif
@if($entry->status === 'approved' || $entry->payroll_id)<span class="help">Locked for editing</span>@endif</td></tr>@empty<tr><td colspan="{{ auth()->user()->isAdmin() ? 5 : 4 }}"><div class="empty"><strong>No hours for this selection.</strong><p>Add hours or choose another month and filter.</p><a class="btn" href="{{ route($routePrefix.'.create') }}">+ Add hours</a></div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination', ['items' => $timesheets])
@endif
</div>@endsection
