@extends('layouts.app')
@section('title', $workforce === 'own' ? 'Attendance & overtime' : 'Rental timesheets')
@section('eyebrow', $workforce === 'own' ? 'Own employees · Attendance' : 'Rental manpower · Hours register')
@section('description', $workforce === 'own' ? 'Record attendance and overtime for your own employees, separately from rental timesheets.' : 'Daily hours, review status, and the entries used to calculate rental salaries.')
@section('actions')<a class="btn" href="{{ route($routePrefix.'.create') }}">+ Add {{ $workforce === 'own' ? 'attendance' : 'hours' }}</a>@endsection
@section('content')<div class="stats" style="grid-template-columns:repeat(3,minmax(0,1fr))"><div class="stat"><div class="label">Filtered regular hours</div><div class="value">{{ \App\Services\Pay::decimal($totals['regular']) }}</div><div class="note">All statuses matching your filters</div></div><div class="stat"><div class="label">Filtered overtime hours</div><div class="value">{{ \App\Services\Pay::decimal($totals['overtime']) }}</div><div class="note">Approval required for overtime pay</div></div><div class="stat"><div class="label">Daily entries</div><div class="value">{{ $timesheets->total() }}</div><div class="note">One record per employee / day</div></div></div>
<div class="card"><form class="filters" method="GET"><div class="field"><label for="month">Month</label><input id="month" type="month" name="month" value="{{ $month }}"></div><div class="field"><label for="company_id">Company</label><select id="company_id" name="company_id"><option value="">All companies</option>@foreach($companies as $company)<option value="{{ $company->id }}" {{ request('company_id') == $company->id ? 'selected' : '' }}>{{ $company->name }}</option>@endforeach</select></div><div class="field"><label for="employee_id">Employee</label><select id="employee_id" name="employee_id"><option value="">All employees</option>@foreach($employees as $employee)<option value="{{ $employee->id }}" {{ request('employee_id') == $employee->id ? 'selected' : '' }}>{{ $employee->name }}</option>@endforeach</select></div><div class="field"><label for="status">Status</label><select id="status" name="status"><option value="">All statuses</option>@foreach(['pending', 'approved', 'rejected'] as $status)<option value="{{ $status }}" {{ request('status') === $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>@endforeach</select></div><button class="btn secondary">Filter</button></form>
<div class="table-wrap"><table><thead><tr><th>Employee / date</th><th>Hours</th><th>Rate snapshot</th><th>Status / notes</th><th>Actions</th></tr></thead><tbody>@forelse($timesheets as $entry)<tr><td><strong>{{ $entry->employee->name }}</strong><span class="sub">{{ $entry->employee->company->name }}</span><span class="sub">{{ $entry->work_date->format('d M Y') }} · by {{ optional($entry->creator)->name }}</span></td><td><strong>{{ \App\Services\Pay::decimal($entry->regular_units) }} regular</strong><span class="sub">{{ \App\Services\Pay::decimal($entry->overtime_units) }} overtime</span></td><td>SAR {{ \App\Services\Pay::decimal($entry->hourly_rate_cents) }} / h<span class="sub">OT × {{ \App\Services\Pay::decimal($entry->overtime_multiplier_units) }}</span><span class="sub">{{ $workforce === 'own' ? 'OT pay' : 'Estimated pay' }}: {{ \App\Services\Pay::money(($workforce === 'own' ? 0 : $entry->regularPay()) + $entry->overtimePay()) }}</span></td><td class="wrap"><span class="badge {{ $entry->status }}">{{ ucfirst($entry->status) }}</span>@if($entry->payroll_id)<span class="badge">Payroll locked</span>@endif @if($entry->notes)<span class="sub">{{ $entry->notes }}</span>@endif @if($entry->review_note)<span class="sub">Review: {{ $entry->review_note }}</span>@endif</td><td>@if($entry->status !== 'approved' && !$entry->payroll_id)<div class="actions"><a class="btn secondary small" href="{{ route($routePrefix.'.edit', $entry) }}">Edit</a><form method="POST" action="{{ route($routePrefix.'.destroy', $entry) }}" data-confirm="Delete this hours entry?">@csrf @method('DELETE')<button class="btn danger small">Delete</button></form></div>@endif
@if(auth()->user()->isAdmin() && $entry->status === 'pending' && !$entry->payroll_id)<div class="actions" style="margin-top:8px"><form method="POST" action="{{ route($routePrefix.'.review', $entry) }}">@csrf<input type="hidden" name="status" value="approved"><button class="btn small">✓ Approve</button></form><details><summary style="font-size:11px;cursor:pointer;color:#a54742">Reject</summary><form class="review-form" method="POST" action="{{ route($routePrefix.'.review', $entry) }}" style="margin-top:6px">@csrf<input type="hidden" name="status" value="rejected"><input name="review_note" required maxlength="1000" placeholder="Reason for rejection" aria-label="Rejection reason"><button class="btn danger small">Reject</button></form></details></div>@endif
@if(auth()->user()->isAdmin() && $entry->status === 'approved' && !$entry->payroll_id)<details style="margin-top:8px"><summary style="font-size:11px;cursor:pointer">Reopen for correction</summary><form class="review-form" method="POST" action="{{ route($routePrefix.'.review', $entry) }}">@csrf<input type="hidden" name="status" value="pending"><input name="review_note" required maxlength="1000" placeholder="Reason for reopening" aria-label="Reopening reason"><button class="btn secondary small">Reopen</button></form></details>@endif
@if($entry->status === 'approved' || $entry->payroll_id)<span class="help">Locked for editing</span>@endif</td></tr>@empty<tr><td colspan="5"><div class="empty"><strong>No hours for this selection.</strong><p>Add hours or choose another month and filter.</p><a class="btn" href="{{ route($routePrefix.'.create') }}">+ Add hours</a></div></td></tr>@endforelse</tbody></table></div>@include('partials.pagination', ['items' => $timesheets])</div>@endsection
