@extends('layouts.app')
@section('title', ($employee->exists ? 'Edit ' : 'Add ').($workforce === 'own' ? 'own employee' : 'rental employee'))
@section('eyebrow', $workforce === 'own' ? 'Own employees · Monthly salary' : 'Rental manpower · Hourly pay')
@section('description', 'Keep identity, experience, company, and pay information together.')
@section('actions')<a class="btn secondary" href="{{ route($routePrefix.'.index') }}">← Employee directory</a>@endsection
@section('content')
@if($companies->isEmpty() || $designations->isEmpty())<div class="notice info">An active company and designation are required. {{ auth()->user()->isAdmin() ? 'Add them from Companies and Designations before creating an employee.' : 'Ask your Super Admin to assign an active company, and add a designation if needed.' }}</div>@endif
<form method="POST" enctype="multipart/form-data" action="{{ $employee->exists ? route($routePrefix.'.update', $employee) : route($routePrefix.'.store') }}">@csrf @if($employee->exists) @method('PUT') @endif
<div class="columns"><div><div class="card"><div class="card-head"><h2>01 · Personal & identity details</h2><span class="muted" style="font-size:11px">* Required fields</span></div><div class="card-body"><div class="form-grid">
<div class="field full"><label for="name">Full name <span class="required">*</span></label><input id="name" name="name" value="{{ old('name', $employee->name) }}" required maxlength="150" placeholder="Employee's full name"></div>
<div class="field"><label for="iqama_number">Iqama number <span class="required">*</span></label><input id="iqama_number" name="iqama_number" value="{{ old('iqama_number', $employee->iqama_number) }}" required pattern="[0-9]{10}" maxlength="10" inputmode="numeric" placeholder="10-digit Iqama number"><p class="help">Unique across rental and own employees.</p></div>
<div class="field"><label for="passport_number">Passport number <span class="required">*</span></label><input id="passport_number" name="passport_number" value="{{ old('passport_number', $employee->passport_number) }}" required maxlength="30" placeholder="Passport number"></div>
<div class="field"><label for="phone">Phone number <span class="required">*</span></label><input id="phone" name="phone" type="tel" value="{{ old('phone', $employee->phone) }}" required maxlength="25" placeholder="+966 5X XXX XXXX"></div>
<div class="field"><label for="blood_group">Blood group <span class="required">*</span></label><select id="blood_group" name="blood_group" required><option value="">Select blood group</option>@foreach(['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'] as $blood)<option value="{{ $blood }}" {{ old('blood_group', $employee->blood_group) === $blood ? 'selected' : '' }}>{{ $blood }}</option>@endforeach</select></div>
<div class="field"><label for="company_id">Company <span class="required">*</span></label><select id="company_id" name="company_id" required><option value="">Select company</option>@foreach($companies as $company)<option value="{{ $company->id }}" {{ old('company_id', $employee->company_id) == $company->id ? 'selected' : '' }}>{{ $company->name }}{{ !$company->is_active ? ' (inactive)' : '' }}</option>@endforeach</select><p class="help"><a href="{{ route('companies.index') }}">{{ auth()->user()->isAdmin() ? 'Manage companies' : 'View assigned companies' }} ↗</a></p></div>
<div class="field"><label for="designation_id">Designation <span class="required">*</span></label><select id="designation_id" name="designation_id" required><option value="">Select designation</option>@foreach($designations as $designation)<option value="{{ $designation->id }}" {{ old('designation_id', $employee->designation_id) == $designation->id ? 'selected' : '' }}>{{ $designation->name }}{{ !$designation->is_active ? ' (inactive)' : '' }}</option>@endforeach</select><p class="help"><a href="{{ route('designations.index') }}">Manage designations ↗</a></p></div>
<div class="field"><label for="joined_on">Joining date <span class="required">*</span></label><input id="joined_on" name="joined_on" type="date" value="{{ old('joined_on', optional($employee->joined_on)->format('Y-m-d')) }}" max="{{ now()->format('Y-m-d') }}" required></div>
<div class="field"><label for="status">Employee status <span class="required">*</span></label><select id="status" name="status">@foreach(['active', 'inactive'] as $status)<option value="{{ $status }}" {{ old('status', $employee->status) === $status ? 'selected' : '' }}>{{ ucfirst($status) }}</option>@endforeach</select></div>
</div></div></div>
<div class="card"><div class="card-head"><h2>02 · Previous experience</h2><span class="badge" data-experience-count>0 / 5</span></div><div class="card-body"><p class="description" style="margin-bottom:17px">Add up to five previous roles. Use + to add and − to remove an entry.</p><div data-experiences>@foreach(old('previous_experience', $employee->previous_experience ?? ['']) as $experience)<div class="experience-row"><textarea name="previous_experience[]" maxlength="2000" placeholder="Company, role, duration, and responsibilities…">{{ $experience }}</textarea><button type="button" class="btn danger small" data-remove-experience>− Remove</button></div>@endforeach</div><button type="button" class="btn secondary small" data-add-experience>+ Add experience</button></div></div></div>
<div><div class="card"><div class="card-head"><h2>Employee photo <span class="required">*</span></h2></div><div class="card-body"><img data-photo-preview src="{{ $employee->exists ? route('employees.photo', $employee) : '' }}" alt="Photo preview" {{ $employee->exists ? '' : 'hidden' }} style="width:110px;height:120px;object-fit:cover;border-radius:9px;margin-bottom:16px"><div class="field"><label for="photo">{{ $employee->exists ? 'Replace photo' : 'Upload photo' }}</label><input id="photo" name="photo" type="file" accept="image/jpeg,image/png,image/webp" data-photo-input {{ $employee->exists ? '' : 'required' }}><p class="help">JPG, PNG or WebP · up to 2 MB. Photos are visible only to users who can access this employee.</p>@if($errors->any())<p class="help">Choose the file again after correcting validation errors.</p>@endif</div></div></div>
<div class="card"><div class="card-head"><h2>Supporting PDF for CV</h2><span class="badge">Optional</span></div><div class="card-body"><div class="field"><label for="document">Upload PDF document</label><input id="document" name="document" type="file" accept="application/pdf"><p class="help">PDF only · up to 10 MB / 30 pages. This document is appended to the generated employee CV. Encrypted PDFs are not supported.</p>@if($employee->document_path)<p class="help">A supporting PDF is attached. Uploading a new document replaces it.</p><label style="margin-top:14px;font-weight:400"><input name="remove_document" type="checkbox" value="1"> Remove the current supporting document</label>@endif</div></div></div>
<div class="card"><div class="card-head"><h2>03 · {{ $workforce === 'own' ? 'Monthly salary setup' : 'Hourly pay setup' }}</h2></div><div class="card-body"><div class="form-grid">
@if($workforce === 'own')<div class="field full"><label for="monthly_salary">Fixed monthly salary (SAR) <span class="required">*</span></label><input id="monthly_salary" type="number" name="monthly_salary" min="0.01" max="999999.99" step="0.01" value="{{ old('monthly_salary', $employee->monthly_salary_cents ? \App\Services\Pay::decimal($employee->monthly_salary_cents) : '') }}" required><p class="help">Full monthly base pay. Attendance does not automatically prorate salary; record any agreed adjustment as a payroll deduction or allowance.</p></div>@endif
<div class="field full"><label for="hourly_rate">{{ $workforce === 'own' ? 'Overtime base rate' : 'Regular hourly rate' }} (SAR/hour) <span class="required">*</span></label><input id="hourly_rate" name="hourly_rate" type="number" min="0.01" max="99999.99" step="0.01" value="{{ old('hourly_rate', $employee->hourly_rate_cents ? \App\Services\Pay::decimal($employee->hourly_rate_cents) : '') }}" required></div>
<div class="field full"><label for="overtime_multiplier">Overtime multiplier <span class="required">*</span></label><input id="overtime_multiplier" name="overtime_multiplier" type="number" min="1" max="5" step="0.01" value="{{ old('overtime_multiplier', \App\Services\Pay::decimal($employee->overtime_multiplier_units)) }}" required><p class="help">For example, 1.50 pays overtime at 1.5 × the hourly rate. Each hours entry keeps a snapshot of these rates.</p></div></div></div></div></div></div>
<div class="form-footer" style="margin-top:0"><a class="btn secondary" href="{{ route($routePrefix.'.index') }}">Cancel</a><button class="btn" {{ $companies->isEmpty() || $designations->isEmpty() ? 'disabled' : '' }}>{{ $employee->exists ? 'Save changes' : 'Create employee' }} →</button></div></form>@endsection
