@extends('layouts.app')
@section('title', 'Employee profile')
@section('eyebrow', $workforce === 'own' ? 'Own employee · Monthly salary' : 'Rental manpower · Hourly pay')
@section('description', 'Identity, experience, hours, and salary history.')
@section('actions')<a class="btn secondary" href="{{ route($routePrefix.'.index') }}">← Directory</a><a class="btn secondary" href="{{ route($routePrefix.'.cv', $employee) }}">↓ Download CV{{ $employee->document_path ? ' + document' : '' }}</a><a class="btn" href="{{ route($routePrefix.'.edit', $employee) }}">Edit profile</a>@endsection
@section('content')<div class="card"><div class="card-body"><div class="profile-top"><img src="{{ route('employees.photo', $employee) }}" alt="{{ $employee->name }}"><div><div class="eyebrow">EMP-{{ str_pad($employee->id, 4, '0', STR_PAD_LEFT) }}</div><h2>{{ $employee->name }}</h2><p class="description" style="margin:5px 0 10px">{{ $employee->designation->name }} · {{ $employee->company->name }}</p><span class="badge {{ $employee->status }}">{{ ucfirst($employee->status) }}</span> <span class="badge">{{ $workforce === 'own' ? 'Own employee' : 'Rental manpower' }}</span></div></div></div></div>
<div class="columns"><div><div class="card"><div class="card-head"><h2>Employee details</h2></div><div class="card-body"><dl class="detail-list"><div><dt>Iqama number</dt><dd>{{ $employee->iqama_number }}</dd></div><div><dt>Passport number</dt><dd>{{ $employee->passport_number }}</dd></div><div><dt>Phone</dt><dd>{{ $employee->phone }}</dd></div><div><dt>Blood group</dt><dd>{{ $employee->blood_group }}</dd></div><div><dt>Joining date</dt><dd>{{ $employee->joined_on->format('d F Y') }}</dd></div><div><dt>Company</dt><dd>{{ $employee->company->name }}</dd></div></dl></div></div><div class="card"><div class="card-head"><h2>Previous experience</h2><span class="badge">{{ count($employee->previous_experience ?? []) }} entries</span></div><div class="card-body">@forelse($employee->previous_experience ?? [] as $experience)<div class="eyebrow">Experience {{ $loop->iteration }}</div><p class="experience-text">{{ $experience }}</p>@empty<p class="description">No previous experience recorded.</p>@endforelse</div></div>
<div class="card"><div class="card-head"><h2>Recent {{ $workforce === 'own' ? 'attendance' : 'timesheets' }}</h2><a href="{{ route($workforce === 'own' ? 'attendance.index' : 'timesheets.index', ['employee_id' => $employee->id]) }}">View hours →</a></div><div class="table-wrap"><table><thead><tr><th>Date</th><th>Regular</th><th>Overtime</th><th>Status</th></tr></thead><tbody>@forelse($timesheets as $entry)<tr><td>{{ $entry->work_date->format('d M Y') }}</td><td>{{ \App\Services\Pay::decimal($entry->regular_units) }} h</td><td>{{ \App\Services\Pay::decimal($entry->overtime_units) }} h</td><td><span class="badge {{ $entry->status }}">{{ ucfirst($entry->status) }}</span>@if($entry->payroll_id)<span class="sub">Payroll locked</span>@endif</td></tr>@empty<tr><td colspan="4"><div class="empty">No hours entered yet.</div></td></tr>@endforelse</tbody></table></div></div></div>
<div><div class="card"><div class="card-head"><h2>{{ $workforce === 'own' ? 'Monthly salary' : 'Pay rates' }}</h2></div><div class="card-body">@if($workforce === 'own')<div class="salary-row"><span>Fixed base / month</span><strong>SAR {{ \App\Services\Pay::money($employee->monthly_salary_cents) }}</strong></div>@endif<div class="salary-row"><span>{{ $workforce === 'own' ? 'Overtime base / hour' : 'Regular / hour' }}</span><strong>SAR {{ \App\Services\Pay::money($employee->hourly_rate_cents) }}</strong></div><div class="salary-row"><span>Overtime multiplier</span><strong>{{ \App\Services\Pay::decimal($employee->overtime_multiplier_units) }} ×</strong></div><p class="help">Rates are snapshotted when hours are entered. Changing employee rates does not change existing entries.</p></div></div><div class="card"><div class="card-head"><h2>Salary history</h2></div><div class="card-body">@forelse($payrolls as $payroll)<div class="company-row"><div><a href="{{ route($workforce === 'own' ? 'salaries.show' : 'payrolls.show', $payroll) }}"><strong>{{ \Carbon\Carbon::createFromFormat('Y-m', $payroll->month)->format('F Y') }}</strong></a><br><small>SAR {{ \App\Services\Pay::money($payroll->net_pay_cents) }}</small></div><span class="badge {{ $payroll->status }}">{{ ucfirst($payroll->status) }}</span></div>@empty<p class="description">No salary records yet.</p>@endforelse</div></div>@if($employee->status === 'active')<div class="card"><div class="card-body"><h3>Archive employee</h3><p class="description" style="margin-bottom:17px">Stops new hour entries while preserving this employee's records.</p><form method="POST" action="{{ route($routePrefix.'.destroy', $employee) }}" data-confirm="Archive this employee? Historical records will be retained.">@csrf @method('DELETE')<button class="btn danger small">Archive employee</button></form></div></div>@endif</div></div>@endsection
